pcap-dag.c
Add tstamp_precision and tstamp_type support to pcap-dag.c.
Update contact details.
The DAG hardware clock may or may not be synchronsied to either the host clock or an external clock reference, so we can't determine which of PCAP_TSTAMP_ADAPTER or PCAP_TSTAMP_ADAPTER_UNSYNCED is accurate. Either will produce the same result.
The only potential concern is that we don't advertise PCAP_TSTAMP_HOST_* so anyone requesting those explicitly will not be able to capture.
=> Add tstamp_type/precision support for DAG capture

pcap-linux.c
The VLAN TPID was hardcoded in pcap-linux.c but recent Linux kernel
supports 802.1ad Q-in-Q.
Since Linux 3.14, kernel gives the TPID value to the userspace when
available.
=> pcap-linux: Obtain VLAN TPID from the kernel when available

configure.in, pcap-linux.c
This allows the creation of 32-bit binaries that are compatible with
64-bit Linux kernels before version 2.6.27.
Original patch credit: David Fifield of the Nmap project
(https://svn.nmap.org/nmap/libpcap/NMAP_MODIFICATIONS/0002-Add-the-disable-packet-ring-configure-option.patch)
=> Add the --disable-packet-ring configure option.

gencode.c, optimize.c, pcap-int.h, pcap/pcap.h, pcap1.h
The goal of supporting raw filters* is to provide libpcap/tcpdump support
for generic BPF insns, including those that are not-supported by libpcap
(e.g., the BPF_MOD/BPF_XOR ops in Linux, or any of the multiple ancillary
loads in linux). It also allows testing new kernel extensions to the
BPF ISA without having to modify libpcap/tcpdump.
We provide support by modifying pcap_compile() so that it first checks
for raw filters. This works for expressions appended in the command line,
and for expressions read from a file ("-F" option). Filters starting
with an integer and a valid separator (',' or '\n') are considered raw.
All other filters are considered (traditional) expressions.
We also make sure that filters compiled from raw filters are left for the
kernel to validate (added …
=> libpcap: added raw filters

Makefile.in, scanner.c.top, scanner.l
This works around _LARGE_FILES difficulties on AIX. See
http://seclists.org/nmap-dev/2012/q1/459 for example.
This is an alternative to the flex-only solution in #359
=> Move the inclusion of config.h to the top of scanner.c

configure.in
These fixes for libpcap accumulated in the Buildroot filesystem builder at http://git.buildroot.org/buildroot/tree/package/libpcap.
=> configure.in cross compile and noMMU fixes

pcap/bpf.h
For a few years I have been using DLT_USER0 147 (user defined) for capturing and saving a serial protocol used by Wattstopper Digital Lighting Management products (see wattstopper.com website) and dissecting via Wireshark and Lua. I'm planning on adding this pcap file logging to a product, and would like to have a DLT defined for this usage. This started with Issue #401.
=> BPF: add new DLT for WattStopper DLM bus protocol

gencode.c, gencode.h, grammar.y, scanner.l
Multipath TCP (MPTCP) is a standardized extension to TCP (see http://tools.ietf.org/html/rfc6824).This pull request add the support for filtering on packets containing at least one MPTCP option.
The BPF code generated is complex and large due to the limitations of BPF (i.e. no loop) so any feedback on how to reduce the code is welcome !
=> Add support for MPTCP filtering

CHANGES, gencode.c, gencode.h, grammar.y, pcap-filter.manmisc.in, scanner.l
"geneve" can be used to filter on Geneve encapsulated packets. It
also allows later filters to look at frames inside the tunnel
headers.
The Geneve protocol is documented here:
http://tools.ietf.org/html/draft-gross-geneve-02
=> Add support for Geneve (Generic Network Virtualization Encapsulation).

pcap-linux.c
This is a port of the patch from a much earlier bug report: https://bugzilla.redhat.com/show_bug.cgi?id=557728
As far as a specific need for this, I encountered a network appliance based on the 32-bit Linux userspace, but it had a 64-bit kernel. This was required for libpcap to function in that environment.
Caveat: my original patch was for an earlier libpcap version. I have only compile-tested this updated version so far.
=> linux 64-bit kernel + 32-bit TPACKET V1 userspace workaround

pcap-linux.c
This is a super-trivial patch, just a couple of things I noticed while reviewing #421
=> remove duplicate includes, align h1_64 with the other struct members

configure.in, pcap-linux.c
These two patches fix two different problems causing together a build failure on noMMU Linux (uClinux) systems like Blackfin.
=> Fix uclinux

scanner.l
This works around _LARGE_FILES difficulties on AIX. See
http://seclists.org/nmap-dev/2012/q1/459 for example.
Original patch credit David Fifield of the Nmap project
(https://svn.nmap.org/nmap/libpcap/NMAP_MODIFICATIONS/pre-configure.patch)
=> Move the inclusion of config.h to the top of scanner.l.

gencode.c
Fixes a memory leak in pcap_compile.
Testcase:
```C
#include <stdio.h>
#include <pcap/pcap.h>
int main()
{
int ret;
const char *bpf = "port 80";
struct bpf_program filter;
if (pcap_compile_nopcap(1524, DLT_EN10MB, &filter, bpf, 0, 0) == -1) {
fprintf(stderr, "Failed to compile bpf filter %s\n", bpf);
return -1;
}
pcap_freecode(&filter);
return 0;
}
```
Valgrind output:
```
$ valgrind --leak-check=full --show-leak-kinds=all ./pcap_test                                      
==13324== Memcheck, a memory error detector                                                                            
==13324== Copyright (C) 2002-2013, and GNU GPL'd, by Julian Seward et al.                                              
==13324== Using Valgrind-3.10.1 and LibVEX; rerun with -h for copyright info …
```
=> Fix memory leak in pcap_compile.

CMakeLists.txt
This allows for out of source builds, and sets HAVE_SOCKLEN_T to fix a compilation error.
=> CMakeLists.txt: Support out of source build. Find socklen_t

Win32/Prj/wpcap.sln, Win32/Prj/wpcap.vcxproj, Win32/Prj/wpcap.vcxproj.filters
It has been discussed in the list: http://seclists.org/tcpdump/2016/q2/51
=> Rename the project files and the output binary on Windows from "libpcap" to "wpcap" for backwards compatibility.

.gitignore, Win32/Prj/wpcap.vcxproj, Win32/Prj/wpcap.vcxproj.filters, pcap-int.h, pcap-new.c, pcap-remote.c, pcap-remote.h, pcap-win32.c, pcap.c, pcap/pcap.h, remote-ext.h, sockutils.c, sockutils.h
Wireshark x64 can capture packets normally under this version ``wpcap.dll`` built from libpcap source. I didn't test other use cases.
For now, only 4 functions are still missing compared to WinPcap:
1. endservent()
2. getservent()
3. wsockinit()
4. pcap_read()
I think 1. and 2. are needed to be added back later. 3. and 4. are some functions maybe we can ignore.
=> Add back WinPcap specific functions to libpcap, the built wpcap.dll already works with Wireshark.

inet.c, missing/win_snprintf.c, pcap-new.c, pcap-remote.c, pcap-win32.c, pcap.c, portability.h, savefile.c, sockutils.c
Mainly for Windows:
``strncpy, strcpy`` -> ``strlcpy`` -> ``strncpy_s``
``strncat, strcat`` -> ``strlcat`` -> ``strncat_s``
``strtok`` -> ``strltok`` -> ``strtok_s``
``scanf`` -> ``scanf_s``
``sprintf`` -> ``pcap_snprintf``
Add ``(u_int)`` to some comparisons
=> Fix some compile warnings reported by MSVC.

pcap-bpf.c
FreeBSD 9.0 and later can use "bintime" format time stamps.  We can easily convert it to microsecond or nanosecond time stamps.
=> Support nanosecond-precision timestamp for FreeBSD.

GenVersion.bat, Win32/Prj/wpcap.vcxproj, version.h.in
This PR is to fix this issue: https://github.com/the-tcpdump-group/libpcap/issues/518
The corresponding change for Npcap is here: https://github.com/nmap/npcap/commit/db8b65da23a77c46624ea6278c15ade077a9e386
=> Libpcap version can be automatically generated based on the source.

pcap.c
Or MSVC will complain:
```
1>  pcap.c
1>..\..\pcap.c(2144): error C2065: 'WINPCAP_VER_STRING' : undeclared identifier
1>..\..\pcap.c(2144): error C2099: initializer is not a constant
1>..\..\pcap.c(2146): error C2065: 'WINPCAP_PRODUCT_NAME' : undeclared identifier
1>..\..\pcap.c(2146): error C2099: initializer is not a constant
1>..\..\pcap.c(2146): error C2143: syntax error : missing ';' before 'string'
1>..\..\pcap.c(2148): error C2065: 'WINPCAP_PRODUCT_NAME' : undeclared identifier
1>..\..\pcap.c(2148): error C2099: initializer is not a constant
1>..\..\pcap.c(2148): error C2143: syntax error : missing ';' before 'string'
1>..\..\pcap.c(2169): warning C4034: sizeof returns 0
1>..\..\pcap.c(2189): warning C4034: sizeof returns 0
1>  savefile.c
1>  scanner.c
1>  sf-pcap-ng.c
1> …
```
=> Also include version strings defined by Npcap/WinPcap on Windows.

Win32/Prj/wpcap.vcxproj
This is to fix MSVC's compile error: ``fatal error C1905: Front end and back end not compatible`` if not using rebuild.
=> Use different intermediate folders for x86 and x64 builds on Windows

Win32/Prj/wpcap.vcxproj, pcap-win32.c
In order to accommodate this pull request, Npcap's Packet API is also changed here: https://github.com/nmap/npcap/commit/73edca1b863cb9fe90a4b92a7a4996a2421b2701 and will take effect in next Npcap 0.10 r7 release.
And BTW this this ``PCAP_IF_LOOPBACK`` flag value still in use? This code is even not enabled for some time, so the flag is not set. However, the loopback interface works just fine with Wireshark or Nmap.
=> Don't need to open the interface any more in order to retrieve the loopback flag on Windows.

pcap-win32.c
Although ``NPF_DRIVER_NAME_NORMAL`` is defined in Npcap's ``WpcapNames.h``, this header is not included directly or indirectly by libpcap, so it's no use.
So I defined a new macro: ``HAVE_NPCAP_PACKET_API`` is currently defined in ``Packet32.h``, which is directly included by libpcap here: https://github.com/nmap/npcap/commit/b2221fd4ddba0c6cd0a5be99b769c6db547a73c6
=> Change the Npcap macro from "NPF_DRIVER_NAME_NORMAL" to "HAVE_NPCAP_PACKET_API", because "NPF_DRIVER_NAME_NORMAL" is not defined in Packet32.h.

pcap-dag.c
It looks like 4418d04 in the upstream introduced a typo where DAG support does not build.
This fix also needs to be cherry-picked to libpcap-1.8 branch.
=> Fixing typo in dag_platform_cleanup() from 4418d04

pcap-linux.c
This commit should address the issue when bpf_filter_with_auxdata returned 0 for valid
packets because offset in filter exceeded tp_snaplen as returned by kernel. If
we filter in cooked mode filter offsets are adjusted because sll_header, we
should do the same for snaplen.
=> bpf: increase snaplen if doing cooked mode userspace filtering

pcap-filter.manmisc.in, scanner.l
Add ECE, CWR and NS bits for TCP header, defined in RFC 3168 and RFC 3540.
=> Add 2 new TCP flags per RFC 3168.

pcap/bpf.h, pcap/dlt.h
ftp://ftp.cs.berkeley.edu/pub/4bsd/README.Impt.License.Change
July 22, 1999
To All Licensees, Distributors of Any Version of BSD:
As you know, certain of the Berkeley Software Distribution ("BSD") source
code files require that further distributions of products containing all or
portions of the software, acknowledge within their advertising materials
that such products contain software developed by UC Berkeley and its
contributors.
Specifically, the provision reads:
"     * 3. All advertising materials mentioning features or use of this software
*    must display the following acknowledgement:
*    This product includes software developed by the University of
*    California, Berkeley and its contributors."
Effective immediately, licensees and distributors are no longer required to …
=> Remove 3rd clause of original BSD license, per:

Makefile.in
Fixes the following error which sometimes shows up on parallel builds:
grammar.y:78:21: fatal error: scanner.h: No such file or directory
#include "scanner.h"
=> Makefile.in: Fix missing dependency

.appveyor.yml, CMakeLists.txt, pcap.c
After umpteen trials and errors, the AppVeyor finally produces a `wpcap.dll` and `wpcap.lib` (I assume that is an import-lib for the former). The build-log is [here](https://ci.appveyor.com/project/gvanem/libpcap).
=> Add .appveyor.yml for MSVC automated builds

pcap-win32.c, portability.h
In MSVC debug-mode (`-MDd` or `-MTd`), there is an important warning on
the redefinition of `strdup`:
```
portability.h(104): warning C4005: 'strdup': macro redefinition
f:\ProgramFiler-x86\WindowsKits\Include\10.0.10586.0\ucrt\crtdbg.h(319):
note: see previous definition of 'strdup'
```
It's definition is:
```
#define strdup(s)  _strdup_dbg(s, _NORMAL_BLOCK, __FILE__, __LINE__)
```
Undoing that in `"portability.h"` would defeat the purpose of `_DEBUG` mode.
=> MSVC's strdup() in _DEBUG mode

rpcapd/daemon.c
When a remote client sent a non null authentication request message (RPCAP_RMTAUTH_PWD), the rpcapd daemon did not respond it and the capture was not able to start.
The counter that stores the bytes read from the received payload was not updated after reading the username. When the procedure was completed, the server kept waiting for more inexistent data, avoiding the start of the capture.
=> rpcapd: The remote capture does not start when the remote client uses the non null authentication procedure.

pcap-linux.c, pcap.c
Linux 4.12 has the vsockmon kernel module for AF_VSOCK packet capture.
AF_VSOCK is used for host<->guest communication between a hypervisor and
virtual machines.  It is supported by VMware and KVM.
Traffic can be captured as follows:
This work was originally written as part of Google Summer of Code 2016 by @GerardGarcia.  I was hist mentor and am upstreaming his code now that Linux 4.12 has been released with vsockmon support.
=> Add link-layer header type for Linux vsock.

CMakeLists.txt
cmake default only builds shared libraries, and also doesn't install library and include files to system.
=> CMAKE add static build and install pcap files

Makefile.in, pcap-int.h, pcap-linux.c, pcap.3pcap.in, pcap.c, pcap/pcap.h, pcap_set_protocol.3pcap
This adds pcap_set_protocol(), which allows you to specify a specific
protocol to be captured.  On Linux, a protocol value specified with
this function will be used instead of ETH_P_ALL when creating and
binding a packet socket.
For ethernet packets, a similar result can be achieved by explicitly
creating a BPF filter that filters on ethertype and attaching that
filter to the packet socket, however, filtering using the packet socket
protocol field is slightly more efficient.
Also, in some cases, the packet socket protocol field and the
ethertype field have different values, and in those cases it is
impossible to achieve the same result by using a BPF filter.  An
example of this is on Arista platforms, where sFlow-sampled packets
are delivered, unmodified, to virtual interfaces on the …
=> Add pcap_set_protocol() to allow specifying a specific capture protocol.

.travis.yml, Makefile.in, config.h.in, configure, configure.ac, pcap-rdmasniff.c, pcap-rdmasniff.h, pcap.c
Implement capture support for offloaded RDMA traffic.  This uses the RDMA
verbs "flow steering" interface, which is available in the Linux kernel
since version 3.12.  The userspace interface is ibv_create_flow() - so
building this support in pcap adds a new dependency on libibverbs.
I added a new "rdmasniff" pcap module, which exposes RDMA devices under an
interface name equal to their libibverbs name.  The module uses the RDMA
verbs interface to create a receive queue with a flow steering rule that
gets a copy of all packets, even offloaded packets generated by or consumed
by the hardware.
I'm definitely not an expert on pcap, so please point out all the places
where I misused APIs or something could be improved.
=> RDMA sniffing support for pcap

CMakeLists.txt
Using NMake in cmake instead MSBUILD causes the build to fail because of a missing version.c file.
Adding a custom command to generate it before building fixes this.
I'm not exactly sure why this step is necessary for NMake but not for MSBUILD.
=> Enable generating version.c from batch file in cmake

CMakeLists.txt, cmake/FindPacket.cmake
I changed things up a little.
I think the most notable benefit of *this* approach is that developers can point to Packet.lib and its headers in numerous other ways now, or just simply have them in their compilers' search path. That wasn't possible before.
So setting the PACKET_DLL_DIR option is optional now. ${HAVE_PACKET32} becomes true if cmake can find the library (and headers) in any others way.
Of course the regular way (-DPACKET_DLL_DIR=/path/to/packet/folder) still works.
In addition, PACKET_DLL_DIR can be set as an environment variable too.
The PacketIsLoopbackAdapter function check now works too. The location of the library had to be provided prior of running the check if it isn't in a system path.
=> Created a FindPacket.cmake module to deal with Packet.lib ins and outs

CMakeLists.txt
The dll's import library as well as the static library are named wpcap.lib.
The static library is created last and deletes the import library.
There's no agreed naming convention for static libraries on MSVC.
A popular conventions is to add the _static suffix to the static library.
Microsoft sometimes adds the lib prefix to their static libraries (libvcruntime.lib, libucrt.lib). This is also how [boost ](http://www.boost.org/doc/libs/1_42_0/more/getting_started/windows.html#library-naming) decided to name their static libraries on MSVC.
I like that, but this may not be obvious to everyone.
The new name for the static is of course up to you.
Another way to fix this is would be to change the output directory. But both libraries are meant to be eventually installed into lib.
=> Fixed naming collision in MSVC builds (cmake)

CMakeLists.txt
- dlls go into bin
- debugging symbols (pdb files generated during debug builds) MUST be install (also into bin)
- only the import library and the static library end up in lib
- MSVC only: 64 bit build MUST go into amd64 sub-folders of both the bin and lib folder
Debugging information are now directly embedded into the static library (/Z7). This should make the it much more self-contained.
As an aside, an end user may want to install the dll to their system path instead.
=> Install things where MSVC and MinGW expect them

optimize.c
Resetting ic->cur_mark to 0 in dot_dump() results in no edges in dot graph
exported for pcap_optimizer_debug > 3 as all blocks are marked with 1 after
running dot_dump_node(); resetting ic->cur_mark to 0 and incrementing it
results in all blocks "marked" when we enter dot_dump_edge().
Fixes: fb2069644165 ("Don't use global state for the BPF compiler.")
=> optimizer: show edges in dot graph

optimize.c
Function vstore() checks if new and old value are the same and if they are,
it replaces the instruction with NOP. We must not do this if both old and
new value are 0 which means "unknown" as in this case, the actual values
(at runtime) can differ so that the instruction cannot be omitted.
An example of a program where this leads to incorrect optimization is shown
in issue #581.
=> optimizer: replacing unknown value with unknown value is not a no-op

CMakeLists.txt
The fact that there are two add_library() targets (one explicitly set to static) causes the BUILD_SHARED_LIBS global flag to not do what it was created for.
Manually conditionalizing it is!
BTW If you could bump up the minimum required cmake version (to at least 2.8.8) things could be done a bit more elegantly.
See [Object Libraries](https://cmake.org/cmake/help/v3.2/command/add_library.html#object-libraries)
This would allow using the same object files to build both static and dynamic libraries.
Doing so manually is not recommended.
=> Fix for BUILD_SHARED_LIBS option

CMakeLists.txt
These 5 commits go together.
BTW Why is the C++ compiler employed? The configuration phase could be speed up (by a few seconds) without it.
=> Use batch files only when building wpcap in cmd.exe

nametoaddr.c, scanner.l
cmd and powershell are not case sensitive, but this file has always been all lowercase.
=> Renamed Wspiapi.h to wspiapi.h

sockutils.c
=>  Define ssize_t as int only when _SSIZE_T_DEFINED is not defined

portability.h
With cmake, strtok_r isn't tested for on windows and assumed not to exist.
Newer version of MinGW have implemented it. Older version (e. g. the one provided by Debian) however seem to only have it under strtok_s.
It's probably a ok to stick with strtok_s for all of windows for now.
=> Use strtok_r as strtok_s under MinGW as well

CMakeLists.txt
This step is necessary to tell cmake to leave out the standard lib prefix on Un*x.
Also, not setting the OUTPUT_NAME target property for ${LIBRARY_NAME}_static on MSVC has the same effect as doing so.
=> Build the shared library without the "lib" prefix on MinGW as well.

CMakeLists.txt
To avoid introducing a hard-to-satisfy dependency on a specific flavor of libgcc_s_*-1.dll, MinGW builds should by default link statically with libgcc. This can be changed by setting USE_STATIC_RT to off.
=> Link with -static-libgcc on MinGW when USE_STATIC_RT is enabled

CMakeLists.txt, cmake/FindPacket.cmake
Using CMAKE_CL_64 is discouraged by cmake's authors and is limited to Windows (MSVC).
=> Use CMAKE_SIZEOF_VOID_P to determine the target architecture.

pcap-types.h, rpcapd/win32-svc.c, sockutils.h
Turns out that neither  or WIN32_LEAN_AND_MEAN have to be defined.
winsock2.h defines _WINSOCKAPI_ and then includes windows.h by itself.
=>  No need to manually define _WINSOCKAPI_

CMakeLists.txt, pcap-dll.rc, rpcapd/rpcapd.rc
The usage of quotes rc files is not very straight forward.
PACKAGE_VERSION_DLL may not be put in quotes except when used for FileVersion. There, it must be in quotes or windres will complain.
PACKAGE_NAME and PACKAGE_VERSION are already carring quotes when arriving form config.h.
So no need to put them in quotes again.
Currently none of these three defines is properly handled by the preprocessor because of this. This PR fixes this.
=> Fixed wrong quote usage in rc files

pcap-rdmasniff.c
A couple of fixes for issues reported by users.  Basically make ctrl-C on tcpdump work better and produce stats output on exit.
=> Small fixes for RDMA sniffing support

optimize.c, pcap/compiler-tests.h, pcap/funcattrs.h
With this change in libpcap tcpdump compiles in 79 seconds instead of 145 seconds. Most importantly, it does not flood the terminal with warnings (https://travis-ci.org/the-tcpdump-group/tcpdump/jobs/287485992 is a good example, see commit message for additional details). I am not sure this is the best solution, though the best I could produce so far.
=> Address CLang "undefined defined" warnings.

CMakeLists.txt
That took a while for what it is.
There are way too many quote signs going on there.
Anyways, cmake's `create_symlink` command is only available on unix. So with MinGW we will search for and use plain `ln`, which BTW doesn't *really* create any symlinks, but simply duplicates and renames the files in question.
In retrospective, this could have been done right from the beginning using some kind of copy routine... great day.
=> Process, install and symlink man pages on MinGW as well

configure, configure.ac
If given --with-libnl (this is equivalent to --with-libnl=yes) then
libpcap will add -Lyes/lib/.libs to the build flags.
=> Fix --with-libnl configure option

gencode.c, pcap-filter.manmisc.in, scanner.l
Hi!
We implemented support for filtering by ICMPv6 header attributes
as part of the Ripe NCC IPv6 Hackathon in Copenhagen.
Using a filter like
`icmp6[icmptype] = icmp6-neighboradvert`
no longer results in
`tcpdump: IPv6 upper-layer protocol is not supported by proto[x]` 
Now it provides the expected result.
=> Added support for ICMPv6 upper layer protocol filtering

cmake/Modules/FindPacket.cmake
1. Changed the modules components to adhere to some "best practices" when writing cmake find modules:
- Find modules should use uppercase names
- Lines should be <= 80 characters long
- Package should include FindPackageHandleStandardArgs
- Package should use FIND_PACKAGE_HANDLE_STANDARD_ARGS
2. (Try to) avoid cmake's sloppy (annoying and outright wrong) practice of using the library's full path on the linker command-line.
e.g. -lC:\User\projects\WpdPack\Lib\Packet.lib
This line also ends up in pcap-config, giving other build systems/compiler a very hard time.
=> Updates and improvements for FindPACKET.cmake

CMakeLists.txt
source files for cmake's check_c_source_compiles() require an entry point
=> Fixed netmap check (cmake)

pcap-netmap.c
Resolve two problems:
1. When uint32_t if_flags is bigger than SHORT_MAX then assigning it to the
short ifr_flags is "implementation-defined" ie. it may give diffrent results
on different compilers/machines (according to C11).
2. When the short ifr_flags has MSB set to 1 then it is "negative signed".
If it will be assigned to the uint32_t if_flags then in result of integer
promotion all bits higer than MSB will be set to 1 and therefore in if_flags
we will see flags that are not really set. This problem affects only FreeBSD
where flags are stored on all 32 bits (on Linux only 16 bits are used).
Using 16-bits mask resolves both problems.
=> Resolve integer conversion problems.

portability.h
=> Avoid redefining HAVE_SNPRINTF

CMakeLists.txt, optimize.c
MSVC's -Wall has more in common with clang's -Weverthing than gcc's -Wall. The result is very overwhelming (3000+ lines of warnings). 
From now on, if building with MSVC *and* if a a .devel is found *and* if MSVC is not using clang as it's front end, increase the warning level to 4. Else do the regular  check_and_add_compiler_option() routine.
It is probably also worth noticing that cmake's compiler identification string for LLVM/Clang is *not* true when using the Clang/C2 toolset. Only something like `if(MSVC AND NOT ${CMAKE_C_COMPILER} MATCHES "clang*")` or `if(CMAKE_GENERATOR_TOOLSET STREQUAL "v140_clang_3_7")` can detect it.
=> Tame -Wall on MSVC and improve Clang/C2 support

pcap-rpcap.c, rpcapd/daemon.c, rpcapd/fileconf.c, rpcapd/rpcapd.c, rpcapd/win32-svc.c, sockutils.c, sockutils.h
SOCK_ASSERT was always called with a true expression ("1") thus only ever executing the message part.
Rename the macro, remove the assert part and remove the "1" parameter.
=> Rename SOCK_ASSERT to SOCK_MESSAGE

CMakeLists.txt, aclocal.m4, rpcapd/rpcapd.c
Question: What is the preferred way to get rid of the fowllowing warnings, where the comments state that this is intentional:
pcap.c:180:19: warning: no previous extern declaration for non-static variable 'pcap_version' [-Wmissing-variable-declarations]
nametoaddr.c:549:28: warning: no previous extern declaration for non-static variable 'eproto_db' [-Wmissing-variable-declarations]
- Create a pcap-deprecated.h file and add it there
- Add DIAG_OFF/ON_MISSING_STATIC macros to diag-control.h
- Add generic DIAG_OFF/ON_WARNING macros to diag-control.h
- Use #pragma clang directly in the code
- Don't enable the warning at all
=> Declare some variables static (found via -Wmissing-variable-declarations)

CMakeLists.txt, aclocal.m4, configure, optimize.c, testprogs/can_set_rfmon_test.c, testprogs/reactivatetest.c
The remaining ocurrences are genuine and intentional.
I have no idea why a "const char *" doesn't qualify but I replaced it with a #define
warning: format string is not a string literal [-Wformat-nonliteral]
=> Add -Wformat-nonliteral and fix most warnings that come up

pcap-npf.c
First reported in 2013 by Sebastian Walther:
https://www.winpcap.org/pipermail/winpcap-bugs/2013-May/001620.html
The hardware packet filters for non-promisc mode on Windows were based
on an incomplete understanding. Npcap developers reviewing MS
documentation agree with Sebastian's assessment and propose the combined
packet filter of NDIS_PACKET_TYPE_ALL_LOCAL | NDIS_PACKET_TYPE_DIRECTED
| NDIS_PACKET_TYPE_BROADCAST | NDIS_PACKET_TYPE_MULTICAST for the
inverse of "promiscuous mode" on Windows.
Packet filter reference:
https://docs.microsoft.com/en-us/windows-hardware/drivers/network/oid-gen-current-packet-filter
=> Expand "non-promisc" packet filter to include edge cases

cmake/Modules/FindDAG.cmake, configure, configure.ac, pcap-dag.c
Link DAG Configuration and Status API library for pcap-dag.
Allows access to statistics such as stream drop, and configuration such as load balancing in future for FANOUT, IF_CONNECTION_STATUS support etc.
The 32-bit DAG stream drop counter provides a better ps_drop value than integrating 16-bit lctr, which may saturate under heavy load.
=> Dag status API

pcap_dump_open.3pcap.in
It isn't stated in the documentation whether the FILE* passed to pcap_dump_fopen() will be closed by a subsequent pcap_dump_close().
This lack of clarity can cause the user to close the FILE* themselves after calling pcap_dump_close(), leading to SIGABRT on some platforms.
=> documentation: make it clear that stream passed to pcap_dump_fopen() is closed by pcap_dump_close()

doc/DLT_ALLOCATE_HOWTO.md, pcap-common.c, pcap/dlt.h
with linktype value 276.
This is a preparation for implementing Linux "cooked" capture
encapsulation v2.
See: GH the-tcpdump-group/libpcap#127
Signed-off-by: Petr Vorel <pvorel@suse.cz>
=> Add DLT_LINUX_SLL2 and LINKTYPE_LINUX_SLL2

pcap-usb-linux.c
fix compilation on musl libc systems like Void Linux and Alpine.
error log if this isn't present.
```
./pcap-usb-linux.c: In function 'usb_findalldevs':
./pcap-usb-linux.c:264:19: error: 'PATH_MAX' undeclared (first use in this function); did you mean 'AF_MAX'?
char usb_mon_dir[PATH_MAX];
^~~~~~~~
AF_MAX
./pcap-usb-linux.c:264:19: note: each undeclared identifier is reported only once for each function it appears in
./pcap-usb-linux.c: In function 'probe_devices':
./pcap-usb-linux.c:419:41: error: 'NAME_MAX' undeclared (first use in this function); did you mean 'AF_MAX'?
char buf[sizeof("/dev/bus/usb/000/") + NAME_MAX];
^~~~~~~~
AF_MAX
make: *** [Makefile:86: pcap-usb-linux.o] Error 1
make: *** Waiting for unfinished jobs....
```
=> pcap-usb-linux.c: add missing limits.h for musl systems.

pcap-dag.c
Suppress libdag warning message to stderr
Needs cherry pick to master also
=> Use 64-bit clean API in dag_findalldevs()

missing/snprintf.c
Per ISO/IEC 9899:201x and POSIX:
As the functions vfprintf, vfscanf, vprintf, vscanf, vsnprintf, vsprintf, and vsscanf invoke the va_arg macro, the value of [args] after the return is indeterminate.
What needs to be done instead is to wrap each invocation of pcap*snprintf with its own pair of va_start and va_end.
=> Fixing va_start/va_end usage

pcap-rpcap.c
I think at this point pr->rmt_sockctrl is still uninitialised, and that we want to discard sockctrl instead.
Please check.
=> Fix using uninitialised file descriptor?

pcap/bpf.h, pcap/pcap.h
This fixes #751.
I'm thinking this may be the proper way to do it, based  on my understanding. I tested a *tcpdump* compilation with this and it worked. If this isn't the right way to do it let me know.
pcap.h will include pcap/pcap.h and pcap/bpf.h that both defines the
bpf_filter and bpf_validate functions.
In most cases this won't be an issue, most people are using the libpcap
as a system library, gcc preprocessor will therefore disable part of the
warnings according to the `3` in
https://gcc.gnu.org/onlinedocs/cpp/Preprocessor-Output.html
In case libpcap is included in a project that actually have more warning
(-Wredundant-decls), and also using local headers we end up having quite
a lot of warning.
=> Fix multiple declaration of bpf_ functions

grammar.y
Fixes #753 
While looking for a way to pass *-Wno-conflicts-sr* from our build framework, I stumbled on something I missed last time I looked at this in the [bison documentation](https://www.gnu.org/software/bison/manual/html_node/Expect-Decl.html) which explains what they suggest is the proper way to fix these warnings.
So here is a patch using just that suggested *expect* in the case of *grammar.y*.
Shift/reduce warnings are apparently mostly harmless:
https://www.gnu.org/software/bison/manual/html_node/Expect-Decl.html
The suggested way to handle them in bison documentation is to monitor
the amount isn't changing over time.
The usual output is:
grammar.y: warning: 38 shift/reduce conflicts [-Wconflicts-sr]
So I added the %expect 38 in grammar.y to avoid warnings.
=> Cleanly avoid warnings in grammar.y

CMakeLists.txt
This is an approach to use CMAKE_CURRENT_SOURCE_DIR intead of CMAKE_SOURCE_DIR.
https://cmake.org/cmake/help/latest/variable/CMAKE_CURRENT_SOURCE_DIR.html
http://johnnado.com/cmake-directory-variables/
http://fujii.github.io/2015/10/10/cmake-best-practice
So its possible add libpcap as subdirectory ( https://cmake.org/cmake/help/v3.0/command/add_subdirectory.html ) in other "cmake-projects".
=> replace CMAKE_SOURCE_DIR by CMAKE_CURRENT_SOURCE_DIR

pcap-rpcap.c
Hi there,
I got two leaks reported by [AddressSanitizer](https://clang.llvm.org/docs/AddressSanitizer.html) from an internal build while communicating with `rpcapd`.
The first from: https://github.com/the-tcpdump-group/libpcap/blob/1fb8e6197ec326da1a5e046c17aee6131f077202/pcap-rpcap.c#L1322
The second from: https://github.com/the-tcpdump-group/libpcap/blob/1fb8e6197ec326da1a5e046c17aee6131f077202/optimize.c#L2375
I gave a quick look around at other back-ends which seem to override `cleanup_op`: https://github.com/the-tcpdump-group/libpcap/blob/1fb8e6197ec326da1a5e046c17aee6131f077202/pcap-int.h#L293
Most of the time, they seem to call `pcap_cleanup_live_common`: https://github.com/the-tcpdump-group/libpcap/blob/1fb8e6197ec326da1a5e046c17aee6131f077202/pcap.c#L3618
Which, in turn, calls …
=> Fix leak in rpcap

nametoaddr.c
Found by oss-fuzz :
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=10919
Apparently, we cannot trust libc to assign value in `getnetbyname_r` even when it returns no error
So, the fix is simple
PS : @guyharris 👍 for all the fixes so far
=> Initializing np value to NULL

pcap-bpf.c
**Steps to reproduce:**
1. Invoke `pcap_open_live("en3", ...)`.
**Expected result:**
1. pcap handle opened successfully.
**Actual result:**
1. `pcap_open_live()` result is NULL, error string is "en3: bpf_load: could not load driver: No such file or directory".
**Analysis**
`sysconfig` called with an invalid kernel extension path. Reason: invalid usage of `sizeof` on a pointer in `bpf_load()` while generating path.
Regression introduced in commit 2d6437c54b9baa77562fc2ae7fc46fb329893441.
=> pcap 1.9.0 does not work on AIX

pcap-bt-linux.c
Minor typo in the comments for error checking if a Bluetooth socket was opened.
One minor consistency fix-up in `pcap_snprintf()`.
=> bt-typo: Extra word existed in comment and minor message fix-ups

pcap-common.c, pcap/dlt.h
Specifically: DLT_VPP_DISPATCH and LINKTYPE_VPP_DISPATCH; update
DLT_MATCHING_MAX and LINKTYPE_MATCHING_MAX
Signed-off-by: Dave Barach <dave@barachs.net>
=> Allocate fd.io vpp dispatch DLT/LINKTYPE values

CMakeLists.txt, Makefile.in, cmake/Modules/Finddpdk.cmake
DPDK (EAL: RTE Version: 'DPDK 18.11.0')can be installed on Ubuntu 18.04 by adding this line
to /etc/apt/sources.list
deb [trusted=yes] http://ftp.se.debian.org/debian/ testing main contrib
and doing sudo apt-get install dpdk dpdk-dev
=> Make CMake work for an installed DPDK on Ubuntu.

pcap-common.c, pcap-linux.c, pcap.c, pcap/dlt.h
Linux kernel 4.20 and greater can report what type of Distributed Switch
Architecture tagging protocol is used on the DSA master/management
interface. We need to map the protocol to a specific DLT and linktype
value in the pcap file because these protocols typically cannot be
decoded simply by making use of heuristics. The sysfs attribute that is
being checked and parsed is documented in this commit:
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=a3d7e01da06013dc580641a1da57c3b482d58157
=> Add support for DSA link-layer types

gencode.c, pcap-common.c, pcap/dlt.h
Link type value to go with 
https://github.com/the-tcpdump-group/tcpdump/pull/734
and
https://bugs.wireshark.org/bugzilla/show_bug.cgi?id=15429
=> Add DLT_/LINKTYPE_ values for IEEE802_15_4_TAP

pcap/pcap.h, sf-pcap.c
#805
Make `pcap_dump_fopen()` a macro on Windows, wrapping the caller's CRT
functions for getting the raw OS file `HANDLE` and calling the exported
hopen variant. `pcap_dump_hopen()` creates a stream from that using
libpcap's CRT and passes that stream to the real `pcap_dump_fopen()`. This
mirrors what was done for `pcap_fopen_offline()`.
=> pcap_dump_fopen differing Windows CRTs work-around 

CMakeLists.txt, Makefile.in, aclocal.m4, config.h.in, configure.ac, pcap-haiku.cpp
This has been getting dust in our ports tree for a while, so I cleaned it up and fixed against latest sources. I believe it's in shape to be upstreamed now.
I didn't include the updated configure (why is this versioned anyway?).
For reference, old patches and recipe [are still in HaikuPorts](https://github.com/haikuports/haikuports/tree/master/net-libs/libpcap).
poke @korli @pulkomandy
=> Haiku port

pcap-common.c, pcap-linux.c, pcap.c, pcap/dlt.h
Following @ffainelli's [work](https://github.com/the-tcpdump-group/libpcap/pull/796) on adding DLT support for DSA tagged master interfaces, this PR adds support for the Marvell DSA and EDSA tagging formats.
=> Add support for (Ethertype) DSA data link types

Makefile.in, gencode.c, pcap.c, pcap/pcap.h, pcap_datalink_val_to_name.3pcap
Introduce pcap_datalink_val_to_description_or_dlt, and
use that when reporting an error.  This was inspired by
seeing `tcpdump: no VLAN support for data link type 113`.
The new equivalent message is
`tcpdump: no VLAN support for Linux cooked`.
=> Report the DLT description in error messages

sockutils.c
Sometimes rpcapd can't rebind due to lingering sockets, here is a basic patch to avoid some of the corner cases.
Closes #765.
=> Allow rpcapd to rebind more rapidly

savefile.c
Currently it was an undefined behavior (UB).
It passes wrong parameters to the fread function call (1 byte, 4 elements).
It should be 4 bytes and 1 element because the `magic` variable is a single 32-bits integer (4 bytes).
```
bytes_read = fread(pointer, number_of_bytes, number_of_elements, file);
```
On some machines the `fread()` call returned 0 with no error from the `ferror()` call for
correct and valid PCAP file.
Reference: https://en.cppreference.com/w/c/io/fread
=> Fixed the fread call in the savefile.c file

optimize.c
Found by oss-fuzz
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=15178
When `opt_init` fails after allocating some of `opt_state` fields, they get double freed : once in `opt_init` and once again in `opt_cleanup` after `opt_error` called `longjmp`
Proposed fix is :
- do not free null pointers (`opt_state` is memset to zero in `bpf_optimize`)
- set pointers to null after we free them in `opt_init`
=> Fixes double free in opt_cleanup

pcap-filter.manmisc.in, scanner.l
Updated pcap-filter.manmisc.in to clarify new token usage
Added an example to pcap-filter.manmisc.in for ip6 protochain for fragments
=> Added support for icmp6 types 1-4 as tokens in scanner.l

pcap.3pcap.in
pcap_set_immediate mode -> pcap_set_immediate_mode
=> Fix missing underscore in pcap man page.

etherent.c, nametoaddr.c
Fixes fencepost error in git commit 5a41835
Closes #846 - testing:
```
% tcpdump -d ether dst host 00:01:03:05:07:09
(000) ld       [2]
(001) jeq      #0x3050709       jt 2    jf 5
(002) ldh      [0]
(003) jeq      #0x1             jt 4    jf 5
(004) ret      #262144
(005) ret      #0
```
=> Nine is a digit.

pcap-netfilter-linux.c
Related to issue #848. Initializes buff array with 0.
=> #848 Fixed valgrind issue with uninitialized bytes

pcap-linux.c
This fixes the offset issue [I mention](https://github.com/the-tcpdump-group/tcpdump/issues/480#issuecomment-486827278) in [tcpdump issue 480](https://github.com/the-tcpdump-group/tcpdump/issues/480) about dumping on multiple interfaces - fix_program() modifies even negative offsets to take the SLL header into account, so the special SKF_AD_ values are not usable directly when using the SLL DLTs.
=> Do not subtract the SLL[2]_HDR_LEN if the location is negative.

pcap-linux.c, testprogs/capturetest.c
This change-set trades off possible over-accounting of packet loss by possible under-accounting it.
The previous way, reading the `rx_dropped` field from `/proc/net/dev` would always count not just what the interface loses (which is what we want), but what the link and upper layers decide to drop.
Instead, the sysfs stats are more accurate, and represent only one event each.
We care about those reported as missed and ones coming from FIFO errors, so we only gather that.
However, not all Linux drivers correctly fill these stats, and use `rx_dropped` as a one-size-fits-all stat.
For these cards, we lose the ability to account for interface-level losses.
Linux defaults that value to 0 in that case, so it follows what the manual specifies.
Due to lack of tools to simulate the loss, I tested …
=> Linux: get ifdrop stats from sysfs.

configure.ac, pcap-linux.c
Removes code supporting SOCK_PACKET, as well as any mentions I could find, and makes the code expect AF_PACKET to be present.
Later on I will be updating with whatever we agree to remove, and will add a simple version check that warns the user if their system is unsupported, as well as the last version supporting it.
=> Linux: remove support for SOCK_PACKET.

nametoaddr.c
getnetbyname is not implemented in Cygwin.
Reference: https://cygwin.com/cygwin-api/std-notimpl.html
=> Fix compilation on Cygwin

ftmacros.h
```
/f/Projects/libpcap/fmtutils.c:114:20: warning: initialization of ‘char *’ from ‘int’ makes pointer from integer without a cast [-Wint-conversion]
114 |  char *errstring = strerror_r(errnum, strerror_buf, PCAP_ERRBUF_SIZE);
|                    ^~~~~~~~~~
```
CMake executes the test for strerror_r with GNU_SOURCE defined,
but the actual application did not define it.
=> Fix compiler warnings on MSYS2/Cygwin

CMakeLists.txt, configure.ac, pcap-linux.c
Since eventfd was introduced in the same release as TPACKET_V2 (2.6.27),
and we require TPACKET_V2 to function, it's a reasonably certain assumption
that we can use eventfd for signaling termination.
=> Linux: expect eventfd.

testprogs/opentest.c
If the `-i` option is not used, the `strdup()` memory was not freed.
To keep the code simpler, use `strdup()` on the `-i` argument.
=> Plug memory-leak

CMakeLists.txt
HAVE_LIBNL is the result of check_function_exists();
check_function_exists() stores its results in cache. As such, setting
BUILD_WITH_LIBNL to FALSE after the initial CMake run didn't work. This
patch fixes that.
=> Unset HAVE_LIBNL if BUILD_WITH_LIBNL is not set

pcap-linux.c
Extracted to a separate function and using sscanf for version parsing to make it easier to follow.
=> Linux: refactor broken TPACKET_V3 detection.

pcap-common.c, pcap/dlt.h
ATSC 3.0 uses a new packet based link layer - ATSC Link-Layer Protocol (ALP) as defined in the ATSC A/330 specification. The link layer typically carries multicast UDP/IPv4 packets and signalling packets.
ATSC 3.0 devices may use this linktype to capture ALP packets and output in pcap format.
(Silicondust makes network attached tuner devices with open APIs for anyone to use)
=> add linktype for ATSC ALP link protocol

gencode.c, gencode.h, grammar.y, pcap-linux.c, scanner.l
Create a filter for the ifIndex field in the LINUX_SLL2 pcap format, and convert it to the right SKF_AD_ value for live captures.
=> A new filter "ifindex" for LINUX_SLL2 and live Linux captures

pcap-filter.manmisc.in
They were never documented (at least since 1999).
The only documented protocols are:
```
ether proto protocol
True if the packet is of ether type protocol.  Protocol can be a
number or one of the names ip, ip6, arp, rarp, atalk, aarp, dec-
net,  sca,  lat,  mopdl, moprc, iso, stp, ipx, or netbeui.
```
(pcap-filter man page)
They are rather old and unlikely to be found in a capture file.
Summary:
```
protocol	value	IANA ieee-802-numbers.xhtml
--------        -----   ---------------------------
decdns		803c	DEC Unassigned
decdts		803e	DEC Unassigned
lanbridge	8038	DEC LANBridge
loopback	9000	Loopback
pup		0200	XEROX PUP
sprite		0500	<UNKWOWN in IANA Registry>
vexp		805b	Stanford V Kernel exp.
vprod		805c	Stanford V Kernel prod.
xns		0600	XEROX NS IDP
```
=> RFC: Remove undocumented and rather old "ether proto" protocols

pcap-npf.c
Minor change. We (Npcap) made a bunch of things `const` a while back, so the compiler issues a warning now for this.
=> Make packet_version_string const to match PacketGetVersion return type LPCSTR

pcap/socket.h
Ws2tcpip.h typedefs socklen_t, so we don't need to do so in socket.h.
=> Windows: Remove the socklen_t typedef.

pcap-linux.c
Release and acquire packets using GCC builtins (compatible with
many other common-place compilers).
Fixes #898.
=> Linux: proper memory sync for PACKET_MMAP.

pcap-linux.c
When no interface is specified, added ipv6 support for platforms that only have AF_INET6 sockets and not AF_INET sockets. 
@brianvv
=> Added Ipv6 support to get_if_ioctl_socket

pcap-filter.manmisc.in
Add "(inclusive)" information to portrange keyword description.
=> Make portrange definition more acurate

CMakeLists.txt
The source files use a relative path, but the working directory when
building is different than when running CMake. Using CMAKE_SOURCE_DIR
fixes this discrepancy.
=> Help CMake find Npcap's version.h

pcap-bt-linux.c, pcap-bt-monitor-linux.c
Fix non-blocking mode with bt-linux and bt-monitor-linux. Previously
when fd was set to non-blocking mode and pcap_dispatch() was called
from application, it returned -1 with errno EAGAIN breaking the api
contract.
Fix is to handle errnos EAGAIN and EWOULDBLOCK so that 0 is returned.
=> Bluetooth: fix non-blocking mode

CMakeLists.txt
CYGWIN doesn't define `WIN32` since 2.8.4.
=> Fix Cygwin/MSYS target directories

CMakeLists.txt
`make install DESTDIR=/path/inst` failed on symlink.
=> Fix symlinking with DESTDIR

cmake/Modules/Finddpdk.cmake
This is not a real issue, just proper to not have the PATH included 2 times.
=> cmake: fix Finddpkd comparison between strings

pcap-npf.c
When encountering the NDIS medium type `NdisMediumIP`, treat the interface as an IP interface.
Related to nmap/npcap#173.
=> pcap-npf.c: handle NdisMediumIP

charconv.c
charconv.c:58: error: ‘EINVAL’ undeclared
error cross-compiling this project for Windows. Used CC i686-w64-mingw32-gcc
=> fixed cross compile for windows

rpcapd/daemon.c
fix unaligned access to structs in daemon_msg_findallif_req() and daemon_seraddr()
if an interface has, for example a 3 char name ( unm ), the pointer for sockaddrout_ipv4
gets an uneven address like 0x1003
an processors with alignment restrictions like arm and mips
the write to sockaddrout_ipv4->family does not write to 0x1003 but to 0x1002
same problem for findalldevs_if
so an local variable is defined which will have the correct alignment and then
the variable is copied to the destination address with memcpy
=> fix unaligned access to structs in rpcapd

pcap-linux.c
Hi,
when freeing the pathstr string in pcap-linux, if for some reason the opened file is not properly opened, pathstr might leak. Moving free(pathstr) outside the if{} should free the variable in either case(fr == NULL or fh != NULL).
=> Possible resource leak in pcap-linux.c

pcap-common.c, pcap/dlt.h
Request for a new Link layer type for Hilscher netANALYZER NG 
Discussion can be found here: 
https://seclists.org/tcpdump/2021/q1/66
=> Added DLT_NETANALYZER_NG and LINKTYPE_NETANALYZER_NG 

grammar.y.in, ieee80211.h, pcap-filter.manmisc.in
As per the IEEE 802.11-2016 std, section 9.2.4.1.3, Table 9-1, the control frame Block Ack Request has the subtype 0b1000 and frame Block Ack has the subtype 0b1001. Add this two control frame subtypes in ieee80211.h so that the 802.11 frames can be filtered using "bar" or "ba" in addition to the other ctl frame subtypes.
=> IEEE 802.11: add support to filter Block Ack Req & Block Ack control frames

pcap.c
`pcap-npf.c`'s `pcap_cleanup_npf()` expects to be able to access `opt.device` in order to restore the monitor mode. This results in a use-after-free when calling `pcap_close()`. Instead, do this free in `pcap_cleanup_live_common()`, just like all the others.
=> Move all cleanup actions to pcap_cleanup_live_common

pcap-npf.c
Make sure we set the error message whenever there's a problem. Catch  a big inconsistency in number of timestamp modes reported (not observed in the wild, but should not be hidden).
=> Better error handling in pcap_create_interface() for pcap-npf.c

pcap-haiku.cpp
Since the introduction of commit #f290068 each pcap-xx file provides its own pcap_lib_version() implementation.
This pull request adds pcap_lib_version() to pcap-haiku as it was missing before, leading to library loading issues on Haiku.
=> Haiku: implement pcap_lib_version

pcap-haiku.cpp
Since the introduction of commit #42c3865 each pcap-xx file provides its own checks and adjustment of the snapshot length.
This pull request adds snaplen checks and adjustment for Haiku.
=> Haiku: adjust snaplen

pcap-common.c, pcap/dlt.h
Zigbee stack ZBOSS by DSR has serial protocol for Network Co-Processor configuration (NCP).
DSR implemented a parser for Wireshark for that protocol.
The idea is to display both serial NCP commands and 802.15.4 traffic in the same log.
NCP serial protocol is not related to 802.15.4 itself, so it will be wrong to base NCP parser on 803.15.4 protocol parser in Wireshark - that is why we need a separate DLK/LINKTYPE.
=> Added linktype for ZBOSS NCP setial protocol.

optimize.c
Standards all say free(NULL) is a safe no-op, but since we *know* fp
is NULL here because of the condition above, there's no need to risk it.
=> Avoid calling free() on known-null pointer

configure, configure.ac
There is no need to have:
--enable-remote         enable remote packet capture [default=no]
--disable-remote        disable remote packet capture
Use only:
--enable-remote         enable remote packet capture [default=no]
=> autoconf: Use AS_HELP_STRING macro in configure.ac for '--enable-remote'

pcap-int.h, pcap-rpcap.c, pcap.c, pcap/pcap.h
Hi!
These changes allow for a username and password to be supplied in the source uri for authentication to a remote pcap source, which should work transparently with existing applications - e.g. `tcpdump` required no changes.
I've tried to follow the existing code style as much as possible, but please let me know if there's anything that needs to be changed.
=> support user/pass in rpcap:// and rpcaps:// source URIs

pcap-common.c, pcap.c, pcap/dlt.h
USB 2.0/1.1/1.0 devices (or 3.x and newer when connected to hosts that
are not Super-Speed capable) operate at one of three speeds:
* Low-Speed (1.5 Mbps)
* Full-Speed (12 Mbps)
* High-Speed (480 Mbps)
While the packets are generally common to all three speeds, there are
some differences that span across different layers. The capture speed
should be available to analyzer and it makes sense to expose it via
speed specific linktypes. Existing USB 2.0/1.1/1.0 captures can be
manually, retroactively updated to speed specific linktype.
Low-Speed device will always operate at Low-Speed, regardless of what
host it is connected to. USB cable connected to Low-Speed device only
ever carries packets sent at Low-Speed.
High-Speed device will operate at High-Speed when connected to High-Speed
capable …
=> Add speed specific USB 2.0/1.1/1.0 linktypes

CMakeLists.txt, configure.ac, pcap-haiku.cpp, rpcap-protocol.h
This fixes #1114.
C++11 forbids declaring types inside typeof and offsetof,
so we drop the macro call and declare the struct separately
for the only use of the call.
=> Fix build on Haiku

pcap-linux.c, testprogs/Makefile.in, testprogs/nonblocktest.c
The eventfd is used to break out of a poll() before it
times out, used by pcap_breakloop().  If we are non-blocking,
then the eventfd is never needed, so we close it.  (And
open a new eventfd if we switch to blocking).
=> Close the eventfd if we are non-blocking

pcap-rpcap.c
Signed-off-by: Li kunyu <kunyu@nfschina.com>
=> pcap-rpcap: remove a redundant semicolon

testprogs/CMakeLists.txt, testprogs/fuzz/fuzz_both.c, testprogs/fuzz/fuzz_pcap.c
This PR enables parallel fuzzing with libFuzzer. Previously the same pcap file name was used to write data buffer. So, parallel libFuzzer workers were overwriting the same file. Now all workers have their own unique temporary file.
=> fuzz: Generate unique temporary file names to enable parallel fuzzing

CHANGES, CMakeLists.txt
This change is used to check the CI with cmake minimal 2.8.12.
=> cmake: Update the minimum required version to 2.8.12 (except Windows)

CMakeLists.txt
Suppresses the CMake CMP0042 OLD deprecation warning (closes #1094)
The CMP0042 NEW behaviour sets the target property `MACOSX_RPATH` to TRUE by default.
However, this behaviour can also be controlled by `CMAKE_MACOSX_RPATH`, which `MAXOSX_RPATH` will default to, if set.
For more information, see CMake docs on [CMP0042](https://cmake.org/cmake/help/latest/policy/CMP0042.html) and [MACOSX_RPATH](https://cmake.org/cmake/help/latest/prop_tgt/MACOSX_RPATH.html#prop_tgt:MACOSX_RPATH).
`CMAKE_MACOSX_RPATH` is only set if undefined, allowing users to change this option.
According to the CMake docs, it should be exactly the same behaviour, but it might be worth somebody with a MacOS device testing this, since I don't have a MacOS device.
=> cmake: suppress CMP0042 OLD deprecated warning

pcap.c, savefile.c
`pcap_open_dead` and `pcap_fopen_offline` has not initialized the `breakloop_op` and `can_set_rfmon_op` callback respectively, if `pcap_breakloop()` is called followed by `pcap_open_dead()` and `pcap_can_set_rfmon()` is called followed by `pcap_fopen_offline()` then the null function pointer crashes will happen.
This commit adds two default implementations `pcap_breakloop_dead` and `sf_cant_set_rfmon` and uses them to initialize those two missed callbacks.
fixes: #1146
Signed-off-by: hopper-vul <hopper.vul@gmail.com>
=> Fix two null pointer crashes of breakloop and can_set_rfmon

pcap-config.in
This is a standard interface for foo-config style scripts, and provides the same information that pkg-config guarantees is available, too.
=> pcap-config: support printing the version

pcap-bpf.c, pcap-int.h, pcap-linux.c, pcap.c, pcap/pcap.h, pcap_init.3pcap
This is useful for Wine WoW64 support where 32-bit Windows applications run in a
64-bit Linux process. We can't pass 64-bit packet pointers back to the caller, obviously,
so we'd need to make a copy. The one shot buffer is a copy already so that would be
be copied twice, in libpcap and in Wine.
This option tells mmap() to allocate the buffers below 2GB so Wine can avoid copying them.
=> Add an option to force memory-mapped buffers to be mapped as accessible to 32-bit code

gencode.c
Currently the non-NetBSD code assumes that long is the maximum alignment needed for anything allocated from the chunk allocator. In practice, on typical 32-bit and 64-bit Unix platforms, this is true, since all the structures stored in it have only pointers and 32-bit integers. However, CHERI (on 64-bit architectures) uses 128-bit capabilities to implement C language pointers, which are a combination of a traditional 64-bit address, 64 bits of metadata and an additional 129th validity tag bit. Due to the use of tagged memory to support this tag bit they must be stored at naturally aligned addresses, i.e. 16 byte aligned, but long is still only 64-bit, since that is the natural machine word size for integer arithmetic, and thus if sdup tries to allocate a string of between 0 and 7 bytes …
=> gencode: Unify NetBSD and non-NetBSD alignment, and make more general

INSTALL.md
Let me know if any new entries do not look right to you. Besides that, I could not make good descriptions for the following files, which seem a bit incomplete:
* `pcap-new.c`
* `pcap-options.c`
* `pcap-rpcap-int.h` -- this one is not included from anywhere and redefines `RPCAP_NETBUF_SIZE`
=> Describe more source files in INSTALL.md.

CHANGES, build.sh, gencode.c, pcap.c
Looks good enough to me, please shout if anything needs improvements.
=> Address a few compiler warnings on Haiku.

grammar.y.in
Those later releases only define yydebug if YYDEBUG is defined and only declare yynerrs as global for non-reentrant parsers, so limit the workarounds for those problems to releases before the 1.9 20170709 release.
=> compiler: limit some Berkeley YACC workarounds to pre-2017-07-09 releases.

build.sh
We're working around the warning they produce for yynerrs in the parser being set but not used.
=> build.sh: remove the check for Clang 15 and 16.

instrument-functions.c, pcap-bpf.c, pcap-dpdk.c
This prevents unnecessary casting.
=> Use the intended date types for variables passed as or compared to other types

sockutils.c
This quiets the compiler since it is not even returned anyway, and is a misleading variable name.
=> Remove unused variable retval in sock_present2network

CHANGES, pcap-airpcap.c, pcap-bpf.c, pcap-bt-linux.c, pcap-bt-monitor-linux.c, pcap-dlpi.c, pcap-haiku.c, pcap-int.h, pcap-libdlpi.c, pcap-nit.c, pcap-pf.c, pcap-rdmasniff.c, pcap-rpcap.c, pcap-sita.c, pcap-snit.c, pcap-usb-linux.c, sf-pcapng.c
This change should avoid these cppcheck warnings:
```
pcap-hurd.c:77:18: warning: 'p->buffer' is of type 'void *'. When using void pointers in calculations, the behaviour is undefined. [arithOperationsOnVoidPointer]
pkt = p->buffer + offsetof(struct net_rcv_msg, packet)
^
pcap-hurd.c:78:8: warning: 'p->buffer+offsetof(struct net_rcv_msg,packet)' is of type 'void *'. When using void pointers in calculations, the behaviour is undefined. [arithOperationsOnVoidPointer]
+ sizeof(struct packet_header) - ETH_HLEN;
^
pcap-hurd.c:79:25: warning: 'p->buffer' is of type 'void *'. When using void pointers in calculations, the behaviour is undefined. [arithOperationsOnVoidPointer]
memmove(pkt, p->buffer + offsetof(struct net_rcv_msg, header),
^
```
Remove some '(u_char *)' casts accordingly.
=> struct pcap: Update buffer type from "void *" to "u_char *"

pcap.c
Wrap WSACleanup() in a routine that calls it but returns nothing, so that the wrapper has the right type for an atexit() routine.
This is cleaner that casting a pointer to WSACleanup(), and should avoid warnings from VS 2022.
=> Add a routine to use as an atexit() routine to clean up Winsock 2.

install-sh
The version of install-sh we have was made over 2 decades ago, and last edited 9 years ago.
I updated the script by running autoreconf -fiv on autoconf 2.71, and autoreconf automatically updated the script.
=> Update install-sh script to the latest available version

gencode.c
With the current behavior, we log the error but try to scan the string anyway. We need to quit if the scanner cannot be initialized.
=> Jump to "quit" label if scanner cannot be initialized

dlpisubs.c, pcap-bpf.c, pcap-linux.c, pcap-netfilter-linux.c, pcap-nit.c, pcap-npf.c, pcap-pf.c, pcap-snit.c, pcap-snoop.c, pcap-tc.c
Some code already was doing that (for example, pcap-bpf.c if fetching the DLT list with an ioctl), and, if you can't allocate a DLT_ list, which is usually pretty small, you may have other memory allocation problems later, so letting the program open an interface (and not get a correct list of all link-layer types supported) may not be worth it.
=> If we can't allocate a DLT_ list, fail.

pcap-util.c
Hi! We've been fuzzing `libpcap` with [sydr-fuzz](https://github.com/ispras/oss-sydr-fuzz) security predicates and we found numeric truncation error in `pcap-util.c:374`.
In function `swap_nflog_header` on line 374 variable `size` has type `uint16_t`, type of value on the right side of operator= is `int` (due to integer promotion), so the numeric truncation may occur. Our tool has found input where value of variable `size` truncates to zero. Then `size` is used in if operators on lines 377 and 383, so the truncation may cause wrong behavior. We suggest to change type `uint16_t` of the variable `size` to type `u_int`.
- OS: ubuntu 20.04
- commit: cff41e58f2fcd2c2ee77e9e25c63813e879657e1
1. Build [docker container](https://github.com/ispras/oss-sydr-fuzz/tree/master/projects/libpcap):
``` …
```
=> Numeric truncation at `pcap-util.c:374`

pcap-netfilter-linux.c
Errno should only be valid when `recv()` returns a `-1`, indicating an
error.
I believe the intended behavior here is for packets_nobufs to
be a counter that reports back how many times `recv()` returns
an `ENOBUFS` during a packet capture. Because of the existing logic
however, `packets_nobufs` begins incrementing for every `recv()` call
once the first `ENOBUFS` error is seen, since `errno` is not reset when
there are no errors returned from `recv()`.
Before (counter deviates from strace):
38069 packets captured
38069 packets received by filter
38061 packets dropped by kernel
% time     seconds  usecs/call     calls    errors syscall
------ ----------- ----------- --------- --------- ----------------
26.47    0.282728           7     38067         3 recvfrom
After (counter matches …
=> nflog: only increment packets_nobufs when recv() returns an error

pcap-linux.c
Realtek switchtag rtl4a (4 bytes long, protocol 0xA) and rtl8_4 (8 bytes
long, protocol 0x04) are Ethertype DSA tags, inserted in the Ethernet
header similar to an 802.1Q tag. Both shares the same Ethertype 0x8899
as other Realtek proprietary protocols.
=> Add support for Realtek (Ethertype) DSA data

pcap-common.c, pcap.c, pcap/dlt.h
Add a link-layer header type for the MDB (Multi-Drop Bus) protocol.
The MDB protocol defines messages between a vending machine controller and peripherals inside the vending machine, e.g. a card reader that processes payments.
Packets with DLT_MDB use a pseudo-header as defined in
https://www.kaiser.cx/pcap-mdb.html
=> Add DLT and linktype for MDB

pcap-usb-linux-common.c
Hi! We've been fuzzing `libpcap` with [sydr-fuzz](https://github.com/ispras/oss-sydr-fuzz) security predicates and we found numeric truncation error in `pcap-usb-linux-common.c:39`.
```
static inline u_int
u_int_sum(u_int a, u_int b)
{
return (((b) <= UINT_MAX - (b)) ? (a) + (b) : UINT_MAX);
}
```
In this function on line 39 variable name `b` was confused with variable `a` in `(b) <= UINT_MAX - (b)` expression and integer overflow occurs here when `b` is quite small and `a` is close to `UINT_MAX`.
- OS: ubuntu 20.04
- commit: f225f8d7464569c7b917015c26ad30a37a5fbbe2
```
pcap-usb-linux-common.c:39:40: runtime error: unsigned integer overflow: 4294967292 + 32261 cannot be represented in type 'unsigned int'
```
=> Integer Overflow at `pcap-usb-linux-common.c:39`

pcap/namedb.h
Include <stdio.h> as this uses "FILE" ("include what you use").
Include <pcap/funcattrs.h> to define those macros *and* PCAP_DEPRECATED() (ditto).
=> Tag pcap-namedb.h routines with PCAP_AVAILABLE_ macros.

pcap-bpf.c
Pull the code to test for it and include the necessary header files *outside* the test for compiling on AIX; it's not an AIX feature, it's a FreeBSD feature.
Fix errors in the zero-copy code.
=> pcap-bpf: fix handling of FreeBSD zero-copy BPF.

pcap-linux.c
If we're not going to be in non-blocking mode, open the event FD in the activate rourinte; we don't need it until we're going to activate it for capturing.
This means we don't need to close it if a non-activated handle is being closed.
Clean up some comments, etc. while we're at it.
Fixes issue #1233.
=> pcap-linux: fix a file descriptor link.

pcap/pcap.h
Remove declarations of routines we no longer provide, and a structure filled in only by one of those routines.
(Are we keeping the remaining MS-DOS stuff around for MS-DOS programs that want to read pcap or pcapng files?)
=> Remove declarations of stuff from removed MS-DOS packet driver code.

pcap/funcattrs.h, pcap/pcap.h, testprogs/capturetest.c, testprogs/nonblocktest.c, testprogs/writecaptest.c
Mark all errbuf arguments as "must not be null".  Perhaps the warnings will prevent people from filing bugs such as #1239.
For most routines that return a success/error code value, warn if the result isn't used.  Perhaps this will reduce the number of "why isn't my code working?" questions, for the cases where the programmer doesn't, for example, bother to check whether pcap_activate() succeeds.
Fix up some test programs to do the checks that they weren't doing in the past.
=> Add some more compile-time checks with __attribute__.

pcap-common.c, pcap.c, pcap/dlt.h
Add a link-layer header type for the DECT New Radio protocol defined in ETSI TS 103 636-4.
=> Add DLT and linktype for DECT_NR.

pcap-rpcap-int.h, pcap-rpcap.c, pcap/pcap.h, pcap/socket.h, rpcap-protocol.c, rpcap-protocol.h, rpcapd/daemon.c, rpcapd/daemon.h, rpcapd/rpcapd.c, sockutils.c, sockutils.h, sslutils.c, sslutils.h
Doing so can cause namespace collisions, as per, for example, https://github.com/firnsy/barnyard2/issues/245.
Instead, define PCAP_SOCKET, and use that.
On Windows, this shouldn't break any APIs, as any code using the two active-mode APIs that return a socket handle would probably be assigning their return values to a SOCKET, and as, on Windows, we're defining PCAP_SOCKET as SOCKET, there would be no type clash.
On UN\*Xes, this might break code that uses one of the two active-mode APIs that return a socket handle if those programs were written to assign the return values of those APIs to a SOCKET, as we're no longer defining SOCKET.  However, as those APIs are only provided if libpcap is built with remote capture support - which is not the default - and as they're somewhat painful to …
=> Don't define SOCKET ourselves.

optimize.c
This pull request is intended to address #945 .  It appears that re-computing the dominator sets as and_pullup and or_pullup change the control flow graph prevents the bug from emerging.
=> [optimizer] Recompute dominators if and/or_pullup succeeds

pcap-hurd.c
The warning for line 37 was:
./pcap-hurd.c:196:35: warning: expression does not compute the number of elements in this array; element type is 'struct bpf_insn', not 'short' [-Wsizeof-array-div]
(filter_array_t_filter, FILTER_COUNT);
^~~~~~~~~~~~
But device_set_filter really does want the size in units of shorts.
=> hurd: Avoid warnings

pcap-linux.c, pcap/can_socketcan.h, pcap/sll.h
Add code to format the CAN XL header in a byte-order-independent fashion; use little-endian, to match, as best as possible, what existing captures (most of which were probably done on little-endian machines) have been done.
Always look at the protocol type and forcibly set or clear the appropriate flags in the header, to increase the chances that they're set correctly.
=> socketcan: fix up CAN/CAN FD support and add CAN XL support.

pcap-linux.c, pcap/can_socketcan.h
Make the structure begin with a 32-bit priority/VCID field, rather than with a 16-bit priority field, an 8-bit VCID field, and an 8-bit reserved field.
Use the SWAP macros to do the byte-swapping.
=> socketcan: simplify the byte-swapping.

CHANGES, pcap-filter.manmisc.in, pcap-hurd.c
This among other things includes a workaround for #1269 and seems to work, but could use more eyeballs, so please proof-read if you can.
=> various improvements and bug fixes for Hurd

testprogs/Makefile.in
In theory, this should pass everywhere, including the illumos CI build, which already uses illumos make.
=> Fix Autoconf builds with illumos make.

CHANGES, CMakeLists.txt, cmakeconfig.h.in, configure.ac, fmtutils.c, pcap.c, pcap_strerror.3pcap
I am reasonably sure it is right to require `strerror()`, but perhaps the pre-compile time checks could be omitted altogether and the compilation could fail the usual way in the unlikely case a system without `strerror()` manages to pass all the other checks that are based on C99. What do you think?
=> Make pcap_strerror() more thread-safe.

sf-pcap.c
When writing a pcap packet record, cast the seconds and microseconds values to bpf_u_int32, as that's the type of the values in the record header.  Update the sell-by date of pcap files; making them unsigned means pcap files don't have a Y2.038K problem, but it does have a Y2.106K problem.
=> The time stamp in pcap packet headers has two unsigned 32-bit values.

CMakeLists.txt, cmakeconfig.h.in
This is expected to pass the CI.
=> CMake: Remove unnecessary header checks.

.appveyor.yml, CHANGES, CMakeLists.txt, configure.ac, doc/README.solaris.md, doc/README.windows.md
libpcap was not working correctly on Solaris 9 already, the test makes it obvious.
=> Require a proof of suitable snprintf(3) implementation.

pcap-linux.c
This is a resend of this already discussed pull request https://github.com/the-tcpdump-group/libpcap/pull/1296
I did a complete re-install of my development machine due to the xz-backdoor issue and did something wrong when performing a rebase of the original libpcap repository. Please consider to merge this simplification.
---
The different CAN frame types are defined by Linux SLL_P types in the sll_protocol field and the length of the frame.
LINUX_SLL_P_CANXL:
The frame length for CAN XL can be 12 + 1 to 12 + 2048 (13 .. 2060) byte. Additionally the CANXL_XLF flag has to be set.
LINUX_SLL_P_CAN and LINUX_SLL_P_CANFD:
The frame length for CAN CC is 16 byte and for CAN FD it is 72 byte. Additionally the CANXL_XLF flag is cleared in CAN CC/FD frames.
Reduce the modification and 'sanitizing' …
=> socketcan: make CAN CC/FD/XL frame handling less invasive

Makefile.in
Don't use the hacks for the rather old SunOS 4.
It's helps to do VPATH builds, e.g. 32-bit, 64-bit in two directories.
(https://www.gnu.org/software/automake/manual/html_node/VPATH-Builds.html)
=> Makefile.in: Update the .c.o build rule

Makefile.in, mkdep, rpcapd/Makefile.in, testprogs/Makefile.in
```
Fix an error on Solaris 10 like:
./mkdep: /opt/solarisstudio12.3/bin/cc -D_STDC_C99=: not found
When configure get some compiler option like:
checking for /opt/solarisstudio12.3/bin/cc option to accept ISO C99...
-D_STDC_C99=
Makefile will contain:
CC = /opt/solarisstudio12.3/bin/cc -D_STDC_C99=
And if we use '-c "$(CC)"' mkdep will set and try to run:
CC="/opt/solarisstudio12.3/bin/cc -D_STDC_C99=", which is incorrect.
Remove the quotes to allow mkdep to set CC with the compiler name and
set flags with the option.
```
=> Makefile.in(s): Fix the depend target / mkdep: Exit if a command fails

configure.ac, rpcapd/Makefile.in
```
Build sslutils.c only if HAVE_OPENSSL is set.
Remark: rpcap-protocol.o, sockutils.o, fmtutils.o and eventually
sslutils.o are prerequisite of libpcap.a thus also for rpcapd.
Fix the following error:
===== SETUP 2: CC=/opt/solarisstudio12.3/bin/suncc CMAKE=no IPV6=no REMOTE=yes =====
[...]
$ make -s CFLAGS=-errwarn=%all -errtags=yes
"sslutils.c", line 34: empty translation unit (E_EMPTY_TRANSLATION_UNIT)
cc: acomp failed for sslutils.c
(It reproduces on OpenCSW unstable10x and Studio 12.3/12.4)
```
=> Autoconf: Fix an E_EMPTY_TRANSLATION_UNIT error

pcap-bt-linux.c, pcap-bt-monitor-linux.c
it may be block with recvmsg function, after call pcap_breakloop function.
=> modify call recvmsg function after check break_loop, with bt-linux and bt-monitor-linux.

fad-getad.c, gencode.c, pcap-netmap.c, pcap.c, testprogs/valgrindtest.c
See:
https://web.archive.org/web/20231206084513/http://www.faqs.org/docs/Linux-HOWTO/GCC-HOWTO.html#INDEX.25
```
"Use __linux__ for this purpose, not linux. Although the latter is defined, it is not POSIX compliant."
In fact, linux is not always defined:
TinyCC does not define linux, but __linux__.
```
=> Use always __linux__ for code that uses Linux-specific features

build.sh, build_common.sh, thread-local.h
Some libpcap calls will not be thread-safe. Print a warning.
TinyCC (aka TCC) can be found at https://bellard.org/tcc/,
https://repo.or.cz/r/tinycc.git or as package on some distros.
=> thread-local: Add a workaround for building with TinyCC

pcap/funcattrs.h
Current TinyCC support __attribute((noreturn)).
=> funcattrs: Update PCAP_NORETURN/PCAP_NORETURN_DEF definitions condition

pcap-rpcap.c
This eliminates one cast, and may also eliminate some compiler warnings that we're assigning to a struct sockaddr_storage * a pointer to a structure that's smaller than a struct sockaddr_storage.
=> rpcap: use struct sockaddr as a type in rpcap_deseraddr().

CHANGES, pcap-bpf.c, pcap-linux.c, pcap.c, pcap/pcap.h, pcap_activate.3pcap
This means "the platform you're on lacks a capture mechanism that supports that device".
This was inspired by some Stack Overflow questions in which the user was probably trying to run a capture program on Windows Services for Linux 1, in which the NT kernel attempts to simulate Linux system calls but does not support packet sockets.
It can, and does, also handle a system in which the BPF capture mechanism is the native capture mechanism but that has no BPF devices.
The hope is that the error message they get will better indicate the underlying problem.
=> Add PCAP_ERROR_CAPTURE_NOTSUP error.

CHANGES, pcap-filter.manmisc.in
Following up  #1273, this change adds a backwards compatibility note to the `pcap-filter` manual page for the `vxlan` keyword, and adds an entry to the changelog for this feature.
=> Changelog and backwards compat notes for VXLAN support

.appveyor.yml
The goal is to avoid this type of error with AppVeyor builds:
appveyor DownloadFile https://www.winpcap.org/install/bin/WpdPack_4_1_2.zip
Error downloading remote file: One or more errors occurred.
Inner Exception: The request was aborted: Could not create SSL/TLS
secure channel.
Command exited with code 2
=> Appveyor: Download WpdPack_4_1_2.zip archive from our repository

pcap-airpcap.c, pcap-bpf.c, pcap-int.h, pcap-linux.c, pcap-netfilter-linux.c, pcap-npf.c, pcap-rpcap.c
For the BPF, Airpcap, and NPF (WinPcap/Npcap) capture mechanisms, each  entry in the buffer read from the capture mechanism is aligned on a word boundary, for some value of "word".  This means that all entries *except for the last of them* has padding at the end.
If we have bp as a pointer to the current entry and ep as a pointer to the end of the buffer, calculated by adding the number of bytes read to a (byte) pointer to the beginning of the buffer, and loop as long as bp < ep, incrementing bp by the length of the entry with padding added, this will put bp *past* the end of the buffer for the last entry, as the last entry lacks padding.
Instead, compute the minimum of the rounded-up length of the entry and the space remaining in the buffer (ep - bp), which means that value will not …
=> Don't increment packet buffer pointers past the end of the data.

pcap.c
These commits fix an issue first reported to security@tcpdump.org. 
Since there were no check on the return value of `opendir`  in [`pcap_findalldevs_ex`](https://github.com/the-tcpdump-group/libpcap/blob/269f6104efcc53d0e009c94e0221658b0a4572ab/pcap.c#L4828), the next call to `readdir` could trigger a null pointer dereference resulting in a SegFault. 
PoC:
```C
char  errbuf[PCAP_ERRBUF_SIZE] = { 0 };
pcap_if_t *allDevs;
int ret = pcap_findalldevs_ex("file://non_existing_file", NULL, &allDevs, errbuf);
```
Thanks for the great library and all the hours spent graciously working on it!
Found by @tregua87
=> Check return value of `opendir` in `pcap_findalldevs_ex` to avoid a null pointer deref

CMakeLists.txt
CMake appears to have the notion that a build is only a cross-compile if the targt *operating system* is different.  This is an incorrect notion, as even if the target is the *same* OS but a different instruction set, you may not be able to do tests that involve compiling and running a program.
Check whether CMAKE_GENERATOR_PLATFORM is set and has a value different from that of CMAKE_HOST_SYSTEM_PROCESSOR and, if that's the case, set CMAKE_CROSSCOMPILING to TRUE.
This should fix issue #1352.
(A different strategy may be necessary for cross-builds with UNIX toolchains.)
=> cmake: treat building for another ISA as a cross-compile.

configure.ac
This change puts them ahead of
"AC_CHECK_SIZEOF([time_t],,[#include <time.h>])"
So, in a future update, AC_SYS_LARGEFILE could be replaced by AC_SYS_YEAR2038_RECOMMENDED for ensuring time_t is Y2038-safe.
(With Autoconf version >= 2.72 and GNU C Library version >= 2.34)
=> Autoconf: Move AC_SYS_LARGEFILE and AC_FUNC_FSEEKO

gencode.c, pcap-npf.c, pcap.3pcap.in, pcap.c, pcap_init.3pcap, portability.h, rpcapd/log.c, testprogs/filtertest.c
`WSACleanup` cannot be called from `atexit()` because that's run in `DllMain` context. Instead, start and cleanup at each use, using existing reference counting functions from `sockutils.c`.
Performance impact ought to be small because these are not frequently-called functions in the lifetime of a capture handle, and because `WSAStartup`/`WSACleanup` are essentially just reference increment/decrement in the common case of an application that has already called `WSAStartup`.
I believe this commit covers all likely situations, with one unlikely exception: the functions in `nametoaddr.c` are exported by the library, though they are not documented in the manpages. They are only called internally from functions within `gencode.c` which should be handled by the startup/cleanup calls in …
=> Call WSAStartup and WSACleanup for each use. Fixes #1333

pcap-linux.c
Free pathstr in all the branches.
=> linux: fix leak in check for mac80211 phydev

pcap-dbus.c
`dbus_connection_pop_message()` transfers a reference to the caller. For the message to be properly disposed of, the caller must drop this transferred reference after it has finished using the returned message object.
Previously this was not done, resulting in every single D-Bus message (including file descriptors) being leaked. Fix that by simply calling `dbus_message_unref()` at the appropriate places.
=> dbus: fix message leak

pcap-linux.c
If we're trying to enter rfmon mode, and an interface is a mac80211 device, and nl80211 reports that it's already NL80211_IFTYPE_MONITOR, don't bother to create another monitor device from it. Just use that device as-is and report success, without setting mondevice.
=> Linux: Don't create extra monitor devices

CMakeLists.txt
1) remove SOURCE parameter from add_custom_command().
It was never a valid parameter, but, prior to CMake 3.31, it was silently ignored.  In 3.31 and later, it's treated as an error by default.
See
https://github.com/the-tcpdump-group/libpcap/pull/1380#issuecomment-2471731576
for a case where this breaks something.
2) expand the "still support old versions of CMake, for the benefit of people with older versions, but avoid deprecation warnings/errors" section to handle the deprecation of pre-3.10 versions by 3.31.
=> CMake: fix to support CMake 3.31.

gencode.c, grammar.y.in, pflog.h
Include <netinet/in.h> in pflog.h, as a case of include-what-you-use (it needs address structures).
=> Remove some apparently-unneeded includes.

CHANGES, CMakeLists.txt, cmakeconfig.h.in, configure.ac, doc/README.dag.md, pcap-dag.c
Here is the first version after clean-ups. It works if used correctly, but still has a few rough edges. Also it makes it easier to see where the current libpcap API is not a perfect fit for a mix of Rx-only and Tx-only devices.
It is not clear if it would be better to reuse the Rx FCS environment variables for Tx, or to query the card for the current parameters to minimise user intervention, or maybe to justify introducing C functions into the API to query/set FCS settings on a `pcap_t`.
Likewise, in this revision libpcap returns an error rather late: from `pcap_read()` when trying to capture from a Tx-only stream and from `pcap_inject()` when trying to transmit into an Rx-only stream.  It would be better to have feedback right from `pcap_activate()` (something such as …
=> DAG: Add experimental packet transmit support.

.appveyor.yml
Add a 32-bit VS 2015 WinPcap build.
Instead of doing two VS 2017 WinPcap 64-bit buidls, do one WinPcap and one Npcap build.
Remove definition of AirPcap_ROOT, as it's no longer used.
(The belng comment will suppress most CI builds, but AppVeyor doesn't recognize it, and some other builders might also not recognize it; this is what we want, as this only changes AppVeyor's YAML file.)
[skip ci]
=> CI: fix which builds are done, remove some remaining AirPcap stuff.

.appveyor.yml, nametoaddr.c, scanner.l, testprogs/filtertest.c
VS 2015 is approximately 10 years old; get tid of the VS 2015 builds.
Add VS 2022 builds; try doing them with and without external capture support.
Remove include of <wspiapi.h>; it's only needed for IPv6 support on Windows 2000, which is almost 25 years old, and it has code that provokes warnings in VS2022 builds.
In filtertest, don't arrange to call WSACleanup() via atexit(), as that causes a pointer casting warning in VS 2022 builds.
(AppVeyor-only, so...)
[skip ci]
=> CI: Remove VS 2015 build, add VS 2022 build.

build.sh
Run "filtertest EN10MB", which makes sure that the filter compiler isn't completely broken, as it was after
df8296449a3ae6db4fd50cd0ecd32f595f14f74c; that wasn't detected by the buildbots until it was committed to the repository and tested in tcpdump builds triggered by the libpcap commit.
=> CI: on UN*Xes, do a smoke test of the filter compiler.

CMakeLists.txt, rpcapd/CMakeLists.txt
Some versions of Visual Studio's C compiler report a warning when compiling an empty translation unit, which is what sslutils.c is if we're building without a TLS library.
=> CMake: don't build with sslutils.c if you don't have a TLS library.

CMakeLists.txt
That's the simplest way to check whether we can use check_c_source_runs() to test for a suitable snprintf; it's easier than trying to find out the target instruction set architecture and comparing it with the host instruction set architecture, as CMake doesn't provide any mechanism to provide the target instruction set architecture, on all platforms, in a form that can be compared with the host instruction set architecture, and even if the target is different, we may be able to run code for that instruction set architecture if, for example, it's a 32-bit version of the instruction set architecture on which the build is being done, or if there's a binary emulator.
=> CMake: check whether check_c_source_runs() works.

CMakeLists.txt, configure.ac
Avoid trying to cast negative values to unsigned types, or doing shifts of signed types, in order not to have the test program fail if we're building with undefined-behavior sanitizers enabled.
Fix #1396.
=> autotools, CMake: fix issues with snprintf test and sanitizers.

.appveyor.yml, cmake/Modules/FindPacket.cmake
Just use CMAKE_GENERATOR_PLATFORM to determine for which architecture we're building, and use that to set the subdirectory of the SDK's Lib directory in which to look for libraries.
Use the -A flag for all generators; according to the CMake documentation, they're supported for all generators in CMake 3.1 and later and, on Windows, we require CMake 3.12 or later.  That ensures that CMAKE_GENERATOR_PLATFORM will be set, so that we can use it to determine the right directory in which to look for pcap libraries.
=> CMake: handle Windows architectures as we do for tcpdump.

CHANGES, pcap-dag.c, pcap-dpdk.c, pcap-int.h, pcap-septel.c, pcap-snf.c
pcap_create() returns NULL for all errors, so tcpdump tries to find evidence of ENODEV in the error buffer in order to retry using a different device name.  That does not work when the error string is "This version of libpcap only supports...", so use a format string that works and place it in pcap-int.h.
```
tcpdump version 5.0.0-PRE-GIT
libpcap version 1.11.0-PRE-GIT (DAG-only)
1.dag0 (alias for dag0:0) [none]
2.dag0:0 (Rx stream 0, 64 MiB, DAG 7.5G2 rev A at 0000:01:00.0) [none]
3.dag1 (alias for dag1:0) [none]
4.dag1:0 (Rx stream 0, 64 MiB, DAG 9.2X2 rev D at 0000:02:00.0) [none]
5.dag16 (alias for dag16:0) [none]
6.dag16:0 (Rx stream 0, 64 MiB, vDAG) [none]
```
Before:
```
tcpdump: This version of libpcap only supports DAG cards
```
After:
```
tcpdump: No such device (this build of …
```
=> Fix "tcpdump -i <n>" for something-only libpcap builds.

.appveyor.yml
Do the Visual Studio tests in 32-bit/64-bit pairs, with all other settings the same.
For VS 2015 and VS 2017, do both WinPcap and Npcap, with AirPcap and remote capture off.
For VS 2019, do both WinPcap and Npcap, with Npcap done both without AirPcap and remote capture and with both AirPcap and remote capture.
(This is a subset of the full matrix, so that we don't take *too* much time.)
Annotate each of the pairs.
=> CI: reorganize AppVeyor tests.

pcap-int.h, pcap.c
Casting from FARPROC, which is the type of the return value of GetProcAddress(), to a function pointer gets a C4191 warning from Visual Studio 2022.
Casting FARPROC to void * and returning the result, and then casting the void * to a function pointer, doesn't get the same warning.
Given that, and given that the equivalent UN*X API, dlsym(), returns a void *, we have pcapint_find_function() return a void *.
=> Have pcapint_find_function() return a void * rather than a FARPROC.

.appveyor.yml
Picked up from 7ed2012c21111fe5e8b35c4232bab3927be71b4c.
=> CI: use a better OpenSSL with Visual Studio 2019 and 2022 builds.

.appveyor.yml
Make the comments in the matrix more like those in the main branch.
-DENABLE_REMOTE=YES is the default; use -DENABLE_REMOTE=NO for tests that don't build with remote capture support, and omit -DENABLE_REMOTE=YES for tests that do.
=> CI: make the AppVeyor matrix more like the main branch.

.appveyor.yml, gencode.c
Fix volatile access warnings by wrapping routines called within a setjmp() in routines that call setjmp() and returns an error if it's been longjmped to.
(backported from commit df8296449a3ae6db4fd50cd0ecd32f595f14f74c)
=> CI: add an ARM64 build for AppVeyor.

CHANGES, pcap-dlpi.c
If handed the name of a logical interface, strip off the logical interface number.  This means that in pcap_findalldevs() we won't skip the logical interfaces and will get the network addresses and netmasks they have.
(It also mean that if you try to capture on a logical interface, it'll capture on the physical interface, but that might be the right thing to do.)
We can't do it earlier in fad-gifc.c and fad-glifc.c, because we have to use the logical interface name when fetching the netmask, etc..
=> dlpi: fix open_dlpi_device() to handle Solaris/HP-UX logical interfaces.

testprogs/TESTrun
Some of the new tests depend on an external factor (`getaddrinfo()`), let's see how this holds on various platforms.
=> TESTrun: Add "port" and "portrange" filter tests.

pcap/can_socketcan.h, pcap/ipnet.h, pcap/sll.h, pcap/vlan.h
Per
https://ipira.berkeley.edu/sites/default/files/amendment_of_4-clause_bsd_software_license.pdf
originally at:
ftp://ftp.cs.berkeley.edu/pub/4bsd/README.Impt.License.Change
Delete the advertising clause 3 of the original 4-clause BSD license from those files with the original provision.
Other files have the provision but mentioning the Computer Systems Engineering Group at LBL.
=> Remove 3rd clause of original BSD licensed files

gencode.c
Not a true bug, since Linux kernel (net/core/filter.c) forces any load from SKF_AD_VLAN_TAG to a BPF_H width. However, this change makes libpcap code easier to understand.
=> Use correct size for VLAN tag load instruction

CHANGES, pcap/bpf.h
It takes the on-the-network length, followed by the captured length, as arguments; apparently, some people (or LLMs?) think, perhaps based on other code that takes the captured length first, that it's the other way around, and their fuzz-testing finds that bug in their code.  See issue #1442.
=> Deprecate bpf_filter().

CHANGES, gencode.c, pcap-int.h, pcap-linux.c, pcap_compile.3pcap.in, pcap_offline_filter.3pcap, pcap_setfilter.3pcap, testprogs/TESTrun, testprogs/filtertest.c
Please proof-read, this looks correct to me, but the changes concern all live captures on Linux, so it is desirable not to break things.
This is one of the related imperfections discussed in #1430.
=> Require a live capture for all Linux BPF extensions.

CMakeLists.txt, build.sh, cmakeconfig.h.in, configure.ac, pcap-linux.c, testprogs/TESTmt.pm, testprogs/TESTrun, testprogs/TESTst.pm, testprogs/filtertest.c
Solaris 10 support for libpcap testing is the main change. I tested it on an old Linux and discovered more breakage in the main code. One bug fix is included and the other (Linux BPF extensions do not detect properly after my recent change) is in my working copy, it requires a bit more finish before committing. Meanwhile let's see if the Perl part passes CI on all recent systems.
=> support old Perl and old Linux better

pcap-linux.c
Many of those entries need their own LINKTYPE_/DLT_? values, including tcpdump and Wireshark support for same, but at least this lets you see raw hex data from a capture.
Fixes #1367.
Supercedes #1451.
=> Linux: handle other DSA tags.

CHANGES, CMakeLists.txt, cmakeconfig.h.in, configure.ac, gencode.c, nametoaddr.c, pcap/namedb.h, testprogs/TESTrun
These changes add initial filter tests for the `gateway` keyword. Manually tested on various systems and found to work as expected except on illumos (did not debug this yet). Let's see what CI results look like (most Buildbot worker hosts have been already been configured to have the new entries in `/etc/hosts` and `/etc/ethers`).
=> external test props

CHANGES, gencode.c, pcap-filter.manmisc.in, testprogs/TESTrun
This makes `byte` deterministic and a strict subset of modern syntax until it is clear when/how to deprecate this primitive.
=> assorted fixups for the "byte" primitive

CMakeLists.txt, configure.ac
The code is immensely hard to keep compiling for every random API change the DPDK folks make. If somebody wants DPDK support, it's on them to make it work.
=> DPDK: don't enable it by default.

CHANGES, gencode.c, testprogs/TESTrun
This implements better validation of some `protocol` forms and cleaner unoptimized filter programs for `port` and `portrange` forms without a protocol qualifier.
=> protocol numbers and ports

gencode.c, gencode.h, testprogs/TESTrun
For some time I've been trying to address a number of imperfections, this is a series of changes that look ready. The first part reorganizes quite a bit of C code in `gencode.c` with the intent to make it easier to follow, but not to change any filter program outputs. The second part does not change much code, but it does reduce the unoptimized filter programs for IPv4 and IPv6 netmasks.
Due to the amount of changes this pull request is going to stay open for at least a week before merging.
=> assorted refactoring and all-zero tetras

gencode.c, testprogs/TESTrun, testprogs/filtertest.c
This is the less straightforward change I mentioned in #1505 earlier.
=> Consolidate MAC-48 address matching code.

CHANGES, pcap-linux.c
The Linux kernel documentation for Netlink says:
"Note that unless the NLM_F_ACK flag is set on the request Netlink will not respond with NLMSG_ERROR if there is no error. To avoid having to special-case this quirk it is recommended to always set NLM_F_ACK." (https://docs.kernel.org/userspace-api/netlink/intro.html#nl-msg-type)
In other places, it suggests that sockets do have Auto-ACK enabled by default, however.
Regardless, follow instructions and always set NLM_F_ACK, and receive messages until we get the ACK.
Fix #1508
=> Linux: Always request and wait for an ACK from nl80211

pcap/can_socketcan.h
The Remote Request Substitution bit is a dominant bit ("0") in the CAN XL frame. As some CAN XL controllers support to access this bit a new CANXL_RRS value has been defined for the canxl_frame.flags element.
Defined in Linux mainline since Linux 6.15
Additionally fixed a typo 'Context' -> 'Content'
=> socketcan: add CAN XL Remote Request Substitution CANXL_RRS bit

pcap-linux.c
If we've already put an error message in handle->errbuf for the "you don't have permission to open a packet socket" or "this kernel (or simulacrum of one, such as WSL1) doesn't support packet sockets" errors, don't trash it with a generic "we got some error trying to create the packet socket, here's the error message for that error code" message.
=> linux: don't trash the "no permission" or "no packet sockets" error.

pcap-linux.c
Hi,  
This PR fixes a resource leak in `pcap-linux.c`.  
If `malloc()` fails after opening a socket, the file descriptor is not closed, which can cause a resource leak.
Added `close(sock_fd);` before returning on allocation failure.
Thank you for the review!
=> Fix resource leak on malloc failure in pcap-linux.c

dlpisubs.c, dlpisubs.h, pcap-dlpi.c, pcap-libdlpi.c
Have a common routine to handle the "that interface doesn't have a DLPI device" error; it takes care of "device name too long to be an interface", "we have no DLPI devices because we're in a shared-IP non-global zone", and "we have no DLPI device for that interface because it's probably not a DLPI interface" (as in "the loopback device on Solaris 10 and before").
On HP-UX, where there's just one /dev/dlpi device, if we don't have permission to open that device, check whether the interface exists and, if not, report "no such interface" - see
https://github.com/the-tcpdump-group/libpcap/issues/1538.
On Solaris with libdlpi, distinguish between "that link name is invalid", in which case we know for certain that the interface doesn't exist, and "no such link", in which case we use the common …
=> dlpi: some restructuring.

pcap-dpdk.c
This doesn't fix them - nothing short of changing the way we generate error message strings will do that - but at least it means we don't get annoyed by them, and it also marks places that would need to be changed if we change the way we generate those error message strings. See #1544 for an issue for making those changes.
This addresses part of #1543.
=> dpdk: suppress -Wformat-truncation warnings.

fad-getad.c
It almost certainly does, but we might as well code defensively.
Thanks to a team of developers from the Univesity of Waterloo for reporting this.
=> Don't assume the netmask has the same length as the interface address.

fmtutils.c
For the four octets of UTF-8 case, it was decrementing the remaining buffer length by 3, not 4.
Thanks to a team of developers from the Univesity of Waterloo for reporting this.
=> Fix a copy-and-pasteo in utf_16le_to_utf_8_truncated().

ethertype.h, nametoaddr.c
Linux has
```c
#define ETH_P_SLOW	0x8809		/* Slow Protocol. See 802.3ad 43B */
#define ETH_P_LLDP	0x88CC		/* Link Layer Discovery Protocol */
```
for these.
SLOW carries IEEE 802.3 LACP, both defined in annex 57A of [802.3-2018](https://ieeexplore.ieee.org/stamp/stamp.jsp?tp=&arnumber=8457469) and LLDP is defined in sexion 79 of the same.
=> Define ETHERTYPE_{SLOW,LLDP} and accept them in pcap_nametoeproto()
