the-tcpdump-group/libpcap

pcap-linux.c
If filtering in userland and capturing on a cooked interface, the packet buffer
being sent to bpf_filter_with_aux_data did not include the sll header, so the
filter was being applied improperly.  The buffer would start at the layer3
header.
This change moves the code to fill out the sll structure and update the bp
pointer to point to it to before the call to bpf_filter_with_aux_data.
=> Make sure the userland filtering happens correctly on cooked interfaces.

bpf/net/bpf_filter.c
Ani was mentioned as the author of initial implementation which resulted in PR #391. However PR description is not visible in git repository. Let's fix that and give him credit in the comment instead.
=> Give credit to Ani Sinha

pcap-netfilter-linux.c
ENOBUFS error is not fatal. There is no need to interrupt pcap_loop()/netfilter_read_linux() when receiving this error.
=> nflog: ENOBUFS error handler.

pcap-bpf.c
Add missing parentheses after return statement in the previous commit.
=> Add missing parentheses.

pcap-win32.c
The PR is for this issue: https://github.com/nmap/nmap/issues/512
=> Fix the issue that pcap_open_live() did not accept device names starting with "rpcap://".

config.h.in, configure, configure.ac, pcap-dag.c
Support capture from DAG capture streams with buffer size configured >2GB.
=> Add Endace DAG large stream support

pcap-snf.c
Also on Windows, device name has IP# so use this as address of interface.
=> Update file to allow building on Windows VS2010.

pcap-linux.c
The aggregated ethernet packets produced by the linux kernel
can't exceed 64K (plus eth overhead), so we can bound accordingly
the snaplen for tpacket_v2 on such devices.
This allows a more efficient usage of the receive buffer;
tcpdump has increased the default snaplen up to 256K in recent
versions, to cope better with USB data, and that leads to
tpacket_v2 rx ring being configured by default with tp_frame_nr
equal to 7, which is very bad for most use-case.
With this change the default tpacket_v2 layout has tp_frame_nr
equal to 32, which is still quite low, but works much better
and is consistent with the previous tcpdump behavior.
Signed-off-by: Paolo Abeni <pabeni@redhat.com>
=> bound snaplen for linux tpacket_v2 to ~64k

gencode.c
Note: for this to work correctly with BPF optimization enabled, the fix for issue #581 (included in pull request #582) is needed.
Commit 04660eb1e561 ("Use BPF extensions in compiled filters") taught
libpcap to use VLAN BPF extensions to implement "vlan" and "vlan <id>"
filters. While this fixed filtering in the case when VLAN information
is in packet metadata (which is more frequent on Linux with recent
kernels), it broke the case when outermost VLAN tag is still in packet
data. Unfortunately, even if kernel supports BPF VLAN extensions, we have
to expect both types of packets.
This means that if the initial SK_AD_VLAN_TAG_PRESENT test is negative, we
need to also check for inline VLAN tag. As this test is done only for some
packets (determined at run time), we need to update variable …
=> Make VLAN filter handle both metadata and inline tags

gencode.c
I missed one mishandled case in my previous pull request. This fixes the logic of the code for "vlan &lt;id&gt;" filter on systems supporting BPF extensions.
=> Fix logic of combined VLAN test

pcap-netfilter-linux.c
As described in #601, here is a fix by saving buffer location and packet counter when max_packet limit was reached.
=> fix linux netfilter with a max packet count

pcap-dbus.c
dbus isn't exactly at home on windows and I am sure no dbus guru.
Any suggestions on how to see whether it runs as expected?
=> excluded unavailable members of pcap_t on windows

pcap-dag.c
Updating for company name/email changes
=> Update company name and email address for Endace DAG

pcap-dag.c
=> Change PCAP_ERRNO to PCAP_ERROR in pcap-dag.c

testprogs/CMakeLists.txt, testprogs/fuzz/CMakeLists.txt, testprogs/fuzz/fuzz_both.c, testprogs/fuzz/fuzz_both.options, testprogs/fuzz/fuzz_filter.c, testprogs/fuzz/fuzz_filter.options, testprogs/fuzz/fuzz_pcap.c, testprogs/fuzz/fuzz_pcap.options, testprogs/fuzz/onefile.c
One target for a pcap file
One target for a bpf filter
We should combine both, but I am not sure what is the best way to do this.
This is for oss-fuzz integration
=> Fuzzing libpcap

pcap-haiku.cpp
Proposing a change to pcap-haiku.cpp to remove commented out code.
This PR does not contain any actual code changes, just cleanup.
=> Minor Cleanups for pcap-haiku.cpp

CMakeLists.txt, cmakeconfig.h.in
New PR based on master, replacing #816.
=> Updated: Detect Npcap's version.h in build tree and set HAVE_VERSION_H

aclocal.m4, configure.ac
Midipix is a new POSIX layer for Microsoft Windows.
=> Fix building shared libpcap library on midipix

pcap-linux.c
Some comments and the accumulator name still reflected the previous, procfs based, drop statistics origin.
=> Linux: fix mentions to stats coming from procfs.

pcap-linux.c
When using the memory mapped packet receive path on Linux, we find
that if the buffer is "large" we get a number of dropped packets.
This number of packets is roughly proportional to the buffer size.
It turns out that these packets are dropped by the kernel in the time
period between the socket being opened and the ring parameter setup
completing (this is where the kernel has to allocate the buffer memory).
To prevent this, we can open the socket on protocol 0, which the kernel
interprets to mean that we don't want to receive any packets at all (this
is described when opening a memory mapped packet socket for TX only).  We
then set the correct protocol once everything is configured.
Fixes issue #843 
Signed-off-by: Mark Marshall <mark.marshall@omicronenergy.com>
=> Set socket protocol only after packet ring configured

doc/README.Win32.md
=> Fix a typo

pcap-linux.c
This also removes some leftovers from non-mmapped mode.
=> Linux: require TPACKET v2.

pcap-usb-linux.c
The DEVICE descriptor alone is not enough for full fledged USB class
(eg. Communications, Audio) dissection. Read CONFIGURATION descriptor
twice. First time just with the mandatory 9 bytes, and then using the
wTotalLength to get full CONFIGURATION. Do not attempt requesting full
65535 bytes as many devices do not return the descriptor in such case.
While the DEVICE and CONFIGURATION descriptors are not allowing full
dissection for all cases (eg. HID devices need also report descriptors)
knowing the CONFIGURATION descriptor makes the dissection possible in
many cases.
=> Probe CONFIGURATION descriptor of connected USB devices

pcap.c
Added DLT_CHOICE entry for ATSC_ALP as recommended in discussion thread on pull request #919
=> add linktype for ATSC ALP link protocol pull#2

pcap-rpcap.c, rpcapd/daemon.c, sockutils.c, testprogs/fuzz/CMakeLists.txt, testprogs/fuzz/fuzz_rclient.c, testprogs/fuzz/fuzz_rserver.c
The interesting target seems to be the server.
There is still performance optimization to be done.
This pull request also includes a small leak fix in pcap-linux.c (as well as the buffer overflows in #797)
=> Fuzz rpcap

INSTALL.md
Signed-off-by: Petr Vorel <pvorel@suse.cz>
=> Mention DLT_LINUX_SLL2 in INSTALL.md [skip ci]

.appveyor.yml
=> AppVeyor: Update Npcap SDK to 1.07

pcap-npf.c
pcap_close() cannot be used at this point (in pcap_create()) since it
calls cleanup_op, which is not set until pcap_activate(). Additionally,
return value of strdup was never checked, and several error conditions
resulted in failing to call PacketCloseAdapter on the temporary adapter.
=> NPF: improve error handling in pcap_create_interface()

pcap-common.c, pcap/dlt.h
Here the Pull Request as requested on mailing list.
=> Added new DLT_AUERSWALD_LOG and LINKTYPE_AUERSWALD_LOG 

configure.ac, pcap-hurd.c
This is the hurd support, from debian patch
=> Add hurd support, from debian

CMakeLists.txt, Makefile.in, configure.ac, pcap-haiku.c
=> Haiku: convert implementation to C

CHANGES, gencode.c, nametoaddr.c, nametoaddr.h, pcap-filter.manmisc.in
Let's see if this passes the usual checks.
=> Clean up DECnet address handling.

pcap-npf.c
Handle both ERROR_NOT_SUPPORTED and "NDIS_STATUS_NOT_SUPPORTED with the Customer bit set" as indications that an attempt to set promiscuous mode was rejected because the adapter doesn't support it, in case the setting of the Customer bit is dropped from the Npcap NPF driver in the future.
While we're at it, shuffle some #defines for status codes to put them together and update comments.
=> npf: clean up handling of errors from setting promiscuous mode.

Makefile.in, bpf_image.c, etherent.c, nametoaddr.c, pcap.c, thread-local.h
This should make some functions thread-safe, even if it doesn't make them fully-reentrant; at least some of them would requiree API changes to full reentrancy.
This should fix #1174.
=> Make some static variables thread-local.

pcap-filter.manmisc.in
=> pcap-filter(7): Add the filter "ifindex interface_index"

CMakeLists.txt
Yes, we should probably fix them at some point, but not Right This Instant.
=> CMake: attempt to suppress deprecation errors.

CMakeLists.txt, INSTALL.md, cmakeconfig.h.in, configure.ac, doc/README.hpux, pcap-dlpi.c
The changes look correct to me, but additional proof-reading would be appreciated. I don't have means to test the remaining HP-UX support.
=> Retire support for HP-UX before 10.20.

CMakeLists.txt, cmakeconfig.h.in
Untested, but it should handle Hurd the same way it's handled by the configure script.
=> CMake: translate the changes for Hurd support from autotools.

pcap-util.c
Pull the byte-swapping code into a common routine, and add support for byte-swapping the multi-byte fields in the CAN XL SocketCAN header.
Rename swap_linux_sll_header()swap_linux_sll2_header() to swap_linux_sll_socketcan_header()/swap_linux_sll2_socketcan_header(), because they're not byte-swapping the SLL/SLL2 headers (which are in a standard byte order), they're byte-swapping the SocketCAN header in the SLL/SLL2 payload.
=> socketcan: byte-swap CAN XL Linux cooked capturs as necessary.

CHANGES, Makefile.in, testprogs/CMakeLists.txt, testprogs/Makefile.in, testprogs/activatetest.c
=> Add a new test program for pcap_activate().

CHANGES, doc/README.haiku.md, pcap-haiku.c
I am going to merge these changes after re-testing one more time on Haiku hrev57585 from the next nightly build.
=> Haiku: Work around more portability issues. [skip ci]

build.sh, diag-control.h, pcap-bpf.c, pcap-int.h, pcap.c, rpcapd/rpcapd.c
Please shout before long if anything looks off.
=> address some more warnings on Solaris and illumos

CHANGES, testprogs/findalldevstest.c
Any objections to make this change?
=> Print MAC addresses in findalldevstest.

build.sh, doc/README.solaris.md, pcap-bpf.c, testprogs/findalldevstest.c
In theory, all CI builds should pass...
=> various cleanups

CHANGES, CMakeLists.txt, cmakeconfig.h.in, configure.ac, optimize.c
Looks safe to me, but if you see how this could go wrong, please shout before long.
=> When necessary, trust the OS to implement ffs().

.cirrus.yml, CHANGES, CMakeLists.txt, Makefile.in, build.sh, build_common.sh, build_matrix.sh
This may result in some build failures because warnings in `testprogs` are errors now.
=> CI: Synchronize with the master branch.

pcap-bpf.c
Don't do it when using mmapped buffers, as that ode path doesn't return those errors.  (Hopefully, there's a way to get them.  If not, time to file a FreeBSD bug.)
=> bpf: handle specific read errors only when reading.

sockutils.c
WSAStartup() and WSACleanup() maintain their count of the number of times WSAStartup() has been called minus the number of times WSACleanup() has been called.  If WSAStartup() is called when that count is zero, it initializes Winsock and, whether the count is zero or not, it increments the count.  If WSACleanup() is called when that count is 1, it shuts down Winsock and whether the count is 1 or not, it decrements the count.
=> sockutils: don't keep our own socket count.

.gitignore, CHANGES, pcap-dag.c
This is going to be merged in about 12 hours.
=> assorted DAG improvements

.appveyor.yml, gencode.c
(Test only on AppVeyor, so:)
[skip ci]
=> CI: add an ARM64 build for AppVeyor.

.appveyor.yml, rpcapd/rpcapd.c
Add builds with remote capture and a newer OpenSSL.
Add ARM64 builds for VS 2019.
=> CI: expand the matrix for AppVeyor.

CHANGES, gencode.c
This is supposed to resolve one of the issues in the way of #1399.
=> Fix DECnet packet filtering on big-endian hosts.

gencode.c
Currently the non-NetBSD code assumes that long is the maximum alignment needed for anything allocated from the chunk allocator. In practice, on typical 32-bit and 64-bit Unix platforms, this is true, since all the structures stored in it have only pointers and 32-bit integers. However, CHERI (on 64-bit architectures) uses 128-bit capabilities to implement C language pointers, which are a combination of a traditional 64-bit address, 64 bits of metadata and an additional 129th validity tag bit. Due to the use of tagged memory to support this tag bit they must be stored at naturally aligned addresses, i.e. 16 byte aligned, but long is still only 64-bit, since that is the natural machine word size for integer arithmetic, and thus if sdup tries to allocate a string of between 0 and 7 bytes …
=> gencode: Unify NetBSD and non-NetBSD alignment, and make more general

.cirrus.yml, CHANGES, Makefile.in, build.sh, build_matrix.sh, testprogs/TESTrun
This revision works on my Linux as expected, let's see if this holds for the other OSes.
=> CI: Implement "make check".

build.sh, testprogs/TESTrun
Let's see if this holds outwith Linux.
=> Add some IPv6 tests to "make check".

.cirrus.yml, testprogs/TESTrun
=> Make the timeout dependency conditional.

testprogs/TESTrun
Let's confirm this new Perl code works everywhere.
=> TESTrun: Condense the output format.

.cirrus.yml, INSTALL.md, Makefile.in, testprogs/TESTmt.pm, testprogs/TESTrun, testprogs/TESTst.pm
Let's see how portable this updated Perl code is.
=> TESTrun: Implement parallel testing.

CMakeLists.txt, aclocal.m4, build.sh, cmake/Modules/Finddpdk.cmake, cmakeconfig.h.in, configure.ac, fad-getad.c, fad-gifc.c, pcap-netmap.c, pcap.c, rpcapd/CMakeLists.txt, testprogs/findalldevstest.c, testprogs/selpolltest.c
The intent here is to make the single-threaded part of the build processes shorter.
This looks about the right number of commits and ready for a CI run. I have tested these changes manually on several OSes to varying extent. This may require some finish later.
=> assorted improvements to the build checks

CHANGES, testprogs/TESTrun, testprogs/filtertest.c
Let's see if this works as expected.
=> misc. improvements

gencode.c, grammar.y.in, testprogs/TESTrun
Some simple changes from my working copy. Let's confirm this does not fail on some OS due to a missing test skip condition.
=> various improvements

gencode.c, testprogs/TESTrun
This is another seemingly simple change that I attempted earlier, found more convoluted than expected and stashed away. Now it is ready and has comments in places that are not as trivial as they seem. Let's see what CI looks like.
=> Refine lookup_proto() and test it better.
